# Generated by Django 4.2.1 on 2023-05-17 10:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BimaCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('mobile', models.CharField(blank=True, max_length=32, null=True)),
                ('fax', models.CharField(blank=True, max_length=32, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=32, null=True)),
                ('timezone', models.TimeField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.bimacorecurrency')),
            ],
            options={
                'ordering': ['name'],
                'permissions': [],
            },
        ),
    ]
