<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-05-21 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

=======
# Generated by Django 4.2.3 on 2024-05-21 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
>>>>>>> origin/ma-branch
    initial = True

    dependencies = [
        ("company", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bimacompany",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.bimacorecurrency"
            ),
        ),
    ]
