# Generated by Django 4.2.2 on 2023-07-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimacompany',
            name='company_registry',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='bimacompany',
            name='footer_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bimacompany',
            name='header_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bimacompany',
            name='vat',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
