# Generated by Django 4.2.2 on 2023-07-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_bimacompany_vat_alter_bimacompany_language_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bimacompany',
            options={'default_permissions': (), 'ordering': ['name'], 'permissions': []},
        ),
        migrations.AlterField(
            model_name='bimacompany',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
