# Generated by Django 4.2.3 on 2023-07-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_bimacompany_options_alter_bimacompany_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bimacompany',
            name='company_registry',
        ),
        migrations.AddField(
            model_name='bimacompany',
            name='ape_code',
            field=models.CharField(blank=True, null=True, verbose_name='Company APE Code'),
        ),
        migrations.AddField(
            model_name='bimacompany',
            name='ape_text',
            field=models.CharField(blank=True, null=True, verbose_name='Company APE Text'),
        ),
        migrations.AddField(
            model_name='bimacompany',
            name='capital',
            field=models.CharField(blank=True, null=True, verbose_name='Company Capital'),
        ),
        migrations.AddField(
            model_name='bimacompany',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Company Date Creation'),
        ),
        migrations.AddField(
            model_name='bimacompany',
            name='date_registration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Company Date Registration'),
        ),
        migrations.AddField(
            model_name='bimacompany',
            name='date_struck_off',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Company Date Struck Off'),
        ),
        migrations.AddField(
            model_name='bimacompany',
            name='rcs_number',
            field=models.CharField(blank=True, null=True, verbose_name='RCS Number'),
        ),
        migrations.AddField(
            model_name='bimacompany',
            name='siren',
            field=models.CharField(blank=True, null=True, verbose_name='Company Siren'),
        ),
        migrations.AddField(
            model_name='bimacompany',
            name='siret',
            field=models.CharField(blank=True, null=True, verbose_name='Company Siret'),
        ),
    ]
