# Generated by Django 4.2.3 on 2023-07-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_bimacompany_company_registry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimacompany',
            name='default_pdf_invoice_format',
            field=models.CharField(blank=True, null=True, verbose_name='Default Invoice format'),
        ),
    ]
