# Generated by Django 4.2.3 on 2023-08-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0006_bimacompany_default_pdf_invoice_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="bimacompany",
            name="default_font_family",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Arial", "Arial"),
                    ("Times New Roman", "Times New Roman"),
                    ("Helvetica", "Helvetica"),
                    ("Verdana", "Verdana"),
                    ("Courier New", "Courier New"),
                    ("Open Sans", "Open Sans"),
                    ("Roboto", "Roboto"),
                    ("Georgia", "Georgia"),
                    ("Montserrat", "Montserrat"),
                    ("Lato", "Lato"),
                ],
                default="arial",
                null=True,
                verbose_name="Police par défaut",
            ),
        ),
        migrations.AddField(
            model_name="bimacompany",
            name="show_template_footer",
            field=models.BooleanField(
                blank=True,
                default=True,
                null=True,
                verbose_name="Afficher le pieds de page",
            ),
        ),
        migrations.AddField(
            model_name="bimacompany",
            name="show_template_header",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="Afficher l'entête"
            ),
        ),
        migrations.AddField(
            model_name="bimacompany",
            name="show_template_logo",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="Afficher le logo"
            ),
        ),
        migrations.AlterField(
            model_name="bimacompany",
            name="default_pdf_invoice_format",
            field=models.CharField(
                blank=True,
                default="sale_document_elegant.html",
                null=True,
                verbose_name="Default Invoice format",
            ),
        ),
    ]
