# Generated by Django 4.2.3 on 2023-08-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0007_bimacompany_default_font_family_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bimacompany",
            name="default_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Arial", "Arial"),
                    ("Times New Roman", "Times New Roman"),
                    ("Helvetica", "Helvetica"),
                    ("Verdana", "Verdana"),
                    ("Courier New", "Courier New"),
                    ("Open Sans", "Open Sans"),
                    ("Roboto", "Roboto"),
                    ("Georgia", "Georgia"),
                    ("Montserrat", "Montserrat"),
                    ("Lato", "Lato"),
                ],
                default="#000000",
                null=True,
                verbose_name="Couleur par défaut",
            ),
        ),
    ]
