# Generated by Django 4.2.3 on 2023-08-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0008_bimacompany_default_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bimacompany",
            name="default_color",
            field=models.CharField(
                blank=True,
                default="#000000",
                null=True,
                verbose_name="Couleur par défaut",
            ),
        ),
    ]
