# Generated by Django 4.2.3 on 2023-08-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0009_alter_bimacompany_default_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bimacompany",
            name="default_font_family",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Arial", "Arial"),
                    ("Times New Roman", "Times New Roman"),
                    ("Helvetica", "Helvetica"),
                    ("Verdana", "Verdana"),
                    ("Courier New", "Courier New"),
                    ("Open Sans", "Open Sans"),
                    ("Roboto", "Roboto"),
                    ("Georgia", "Georgia"),
                    ("Montserrat", "Montserrat"),
                    ("Lato", "Lato"),
                ],
                default="Arial",
                null=True,
                verbose_name="Police par défaut",
            ),
        ),
    ]
