# Generated by Django 4.2.3 on 2023-09-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0010_alter_bimacompany_default_font_family"),
    ]

    operations = [
        migrations.AddField(
            model_name="bimacompany",
            name="end_working_day",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ],
                default=4,
            ),
        ),
        migrations.AddField(
            model_name="bimacompany",
            name="start_working_day",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="bimacompany",
            name="vacation_coefficient",
            field=models.FloatField(default=1.82),
        ),
    ]
