# Generated by Django 4.2.3 on 2024-05-21 10:01

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BimaHrActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In Progress"),
                            ("CANCELED", "Canceled"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="IN_PROGRESS",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BimaHrActivityParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "presence_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CONFIRM", "CONFIRM"),
                            ("CANCEL", "CANCEL"),
                            ("MAYBE", "MAYBE"),
                            ("NOT_SPECIFIED", "Not Specified"),
                        ],
                        default="NOT_SPECIFIED",
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BimaHrActivityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=28)),
                ("description", models.TextField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BimaHrApplicantPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "expected_salary",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                (
                    "proposed_salary",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                (
                    "accepted_salary",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("comments", models.TextField(max_length=256)),
                (
                    "source_name",
                    models.TextField(
                        blank=True, default=None, max_length=256, null=True
                    ),
                ),
                ("score", models.FloatField(blank=True, default=None, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PASSED", "Passed"),
                            ("FAILED", "Failed"),
                            ("REFUSED", "Refused"),
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                        ],
                        max_length=64,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BimaHrContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("CDD", "CDD"),
                            ("CDI", "CDI"),
                            ("CVP", "CVP"),
                            ("INTERNSHIP", "Internship"),
                            ("KARAMA", "Karama"),
                        ],
                        max_length=16,
                    ),
                ),
                ("salary", models.DecimalField(decimal_places=3, max_digits=10)),
                ("note", models.TextField(blank=True, null=True)),
                ("job_description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("EXPIRED", "Expired"),
                            ("TERMINATED", "Terminated"),
                        ]
                    ),
                ),
                ("stopped_at", models.DateField(blank=True, null=True)),
                ("reactivated_at", models.DateField(blank=True, null=True)),
                (
                    "reason_stopped",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "termination_reason_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MUTUAL_TERMINATION", "Mutual Termination"),
                            ("DISMISSAL", "Dismissal"),
                            ("RESIGNATION", "Resignation"),
                            ("CONTRACT_TERMINATION", "Contract Termination"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "suspension_reason_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SICK_LEAVE", "Sick Leave"),
                            ("MATERNITY_LEAVE", "Maternity Leave"),
                            ("PROFESSIONAL_TRAINING", "Professional Training"),
                            ("WORK_ACCIDENT", "Work Accident"),
                            ("DISCIPLINARY_SUSPENSION", "Disciplinary Suspension"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("probation_end_date", models.DateField(blank=True, null=True)),
                ("exit_notice_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "permissions": [],
            },
        ),
        migrations.CreateModel(
            name="BimaHrContractAmendment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("amendment_date", models.DateField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "new_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("new_start_date", models.DateField(blank=True, null=True)),
                ("new_end_date", models.DateField(blank=True, null=True)),
                ("other_changes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("EXPIRED", "Expired"),
                            ("TERMINATED", "Terminated"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BimaHrInterview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("note", models.TextField(max_length=255)),
                ("score", models.FloatField(blank=True, null=True)),
                ("comments", models.TextField(blank=True, max_length=256, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PASSED", "Passed"),
                            ("FAILED", "Failed"),
                            ("REFUSED", "Refused"),
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                        ],
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "refusal_reason",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("refusal_date", models.DateField(blank=True, null=True)),
                ("additional_comments", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-date"],
                "permissions": [],
            },
        ),
        migrations.CreateModel(
            name="BimaHrInterviewStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "interview_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TECHNICAL", "Technical"),
                            ("HR", "Hr"),
                            ("INITIAL", "Initial"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
                "permissions": [],
            },
        ),
        migrations.CreateModel(
            name="BimaHrJobCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
                "permissions": [],
            },
        ),
        migrations.CreateModel(
            name="BimaHrPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "unique_id",
                    models.CharField(blank=True, max_length=32, null=True, unique=True),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("MALE", "Male"), ("FEMALE", "Female")], max_length=16
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SINGLE", "Single"),
                            ("MARRIED", "Married"),
                            ("DIVORCED", "Divorced"),
                            ("WIDOWED", "Widowed"),
                            ("SEPARATED", "Separated"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("num_children", models.IntegerField(blank=True, default=0, null=True)),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(max_length=64)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "place_of_birth",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("nationality", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "identity_card_number",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                (
                    "second_phone_number",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "education_level",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "latest_degree",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("latest_degree_date", models.DateField(blank=True, null=True)),
                ("institute", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BimaHrPersonExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("company_name", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("date_begin", models.DateField()),
                ("date_end", models.DateField(blank=True, null=True)),
                ("is_current_position", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BimaHrPersonSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BimaHrPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "work_location",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "seniority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("JUNIOR", "Junior"),
                            ("MID_LEVEL", "Mid-level"),
                            ("SENIOR", "Senior"),
                            ("EXECUTIVE", "Executive"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("requirements", models.TextField(blank=True, null=True)),
                ("responsibilities", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["title"],
                "permissions": [],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="BimaHrSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "permissions": [],
            },
        ),
        migrations.CreateModel(
            name="BimaHrSkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
                "permissions": [],
            },
        ),
        migrations.CreateModel(
            name="BimaHrVacation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "vacation_type",
                    models.CharField(
                        choices=[
                            ("ANNUAL", "Annual"),
                            ("SICK", "Sick"),
                            ("UNPAID", "Unpaid"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REFUSED", "Refused"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("reason_refused", models.TextField(blank=True, null=True)),
                ("request_date", models.DateTimeField(auto_now_add=True)),
                ("status_change_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "permissions": [],
            },
        ),
        migrations.CreateModel(
            name="HistoricalBimaHrActivity",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("updated", models.DateTimeField(blank=True, editable=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In Progress"),
                            ("CANCELED", "Canceled"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="IN_PROGRESS",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical bima hr activity",
                "verbose_name_plural": "historical bima hr activitys",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalBimaHrApplicant",
            fields=[
                (
                    "bimahrperson_ptr",
                    models.ForeignKey(
                        auto_created=True,
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        related_name="+",
                        to="hr.bimahrperson",
                    ),
                ),
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("updated", models.DateTimeField(blank=True, editable=False)),
                (
                    "unique_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=32, null=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("MALE", "Male"), ("FEMALE", "Female")], max_length=16
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SINGLE", "Single"),
                            ("MARRIED", "Married"),
                            ("DIVORCED", "Divorced"),
                            ("WIDOWED", "Widowed"),
                            ("SEPARATED", "Separated"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("num_children", models.IntegerField(blank=True, default=0, null=True)),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(max_length=64)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "place_of_birth",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("nationality", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "identity_card_number",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                (
                    "second_phone_number",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "education_level",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "latest_degree",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("latest_degree_date", models.DateField(blank=True, null=True)),
                ("institute", models.CharField(blank=True, max_length=128, null=True)),
                ("priority", models.SmallIntegerField()),
                ("availability_days", models.IntegerField()),
                ("description", models.TextField(max_length=256)),
                ("comments", models.TextField(max_length=256)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical bima hr applicant",
                "verbose_name_plural": "historical bima hr applicants",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalBimaHrContract",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("updated", models.DateTimeField(blank=True, editable=False)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("CDD", "CDD"),
                            ("CDI", "CDI"),
                            ("CVP", "CVP"),
                            ("INTERNSHIP", "Internship"),
                            ("KARAMA", "Karama"),
                        ],
                        max_length=16,
                    ),
                ),
                ("salary", models.DecimalField(decimal_places=3, max_digits=10)),
                ("note", models.TextField(blank=True, null=True)),
                ("job_description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("EXPIRED", "Expired"),
                            ("TERMINATED", "Terminated"),
                        ]
                    ),
                ),
                ("stopped_at", models.DateField(blank=True, null=True)),
                ("reactivated_at", models.DateField(blank=True, null=True)),
                (
                    "reason_stopped",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "termination_reason_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MUTUAL_TERMINATION", "Mutual Termination"),
                            ("DISMISSAL", "Dismissal"),
                            ("RESIGNATION", "Resignation"),
                            ("CONTRACT_TERMINATION", "Contract Termination"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "suspension_reason_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SICK_LEAVE", "Sick Leave"),
                            ("MATERNITY_LEAVE", "Maternity Leave"),
                            ("PROFESSIONAL_TRAINING", "Professional Training"),
                            ("WORK_ACCIDENT", "Work Accident"),
                            ("DISCIPLINARY_SUSPENSION", "Disciplinary Suspension"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("probation_end_date", models.DateField(blank=True, null=True)),
                ("exit_notice_date", models.DateField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical bima hr contract",
                "verbose_name_plural": "historical bima hr contracts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="BimaHrApplicant",
            fields=[
                (
                    "bimahrperson_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="hr.bimahrperson",
                    ),
                ),
                ("priority", models.SmallIntegerField()),
                ("availability_days", models.IntegerField()),
                ("description", models.TextField(max_length=256)),
                ("comments", models.TextField(max_length=256)),
            ],
            options={
                "ordering": ["first_name"],
                "permissions": [],
            },
            bases=("hr.bimahrperson",),
        ),
        migrations.CreateModel(
            name="BimaHrEmployee",
            fields=[
                (
                    "bimahrperson_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="hr.bimahrperson",
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PERMANENT", "Permanent"),
                            ("TEMPORARY", "Temporary"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "work_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ONSITE", "Onsite"),
                            ("REMOTE", "Remote"),
                            ("HYBRID", "Hybrid"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FULL_TIME", "Full-time"),
                            ("PART_TIME", "Part-time"),
                            ("INTERN", "Intern"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        blank=True,
                        choices=[("ACTIVE", "Active"), ("TERMINATED", "Terminated")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("hiring_date", models.DateField(blank=True, null=True)),
                ("probation_end_date", models.DateField(blank=True, null=True)),
                ("last_performance_review", models.DateField(blank=True, null=True)),
                (
                    "salary",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("balance_vacation", models.FloatField(default=0)),
                ("virtual_balance_vacation", models.FloatField(default=0)),
            ],
            options={
                "ordering": ["first_name"],
                "permissions": [],
                "default_permissions": (),
            },
            bases=("hr.bimahrperson",),
        ),
        migrations.CreateModel(
            name="HistoricalBimaHrEmployee",
            fields=[
                (
                    "bimahrperson_ptr",
                    models.ForeignKey(
                        auto_created=True,
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        related_name="+",
                        to="hr.bimahrperson",
                    ),
                ),
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("updated", models.DateTimeField(blank=True, editable=False)),
                (
                    "unique_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=32, null=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("MALE", "Male"), ("FEMALE", "Female")], max_length=16
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SINGLE", "Single"),
                            ("MARRIED", "Married"),
                            ("DIVORCED", "Divorced"),
                            ("WIDOWED", "Widowed"),
                            ("SEPARATED", "Separated"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("num_children", models.IntegerField(blank=True, default=0, null=True)),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(max_length=64)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "place_of_birth",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("nationality", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "identity_card_number",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                (
                    "second_phone_number",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "education_level",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "latest_degree",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("latest_degree_date", models.DateField(blank=True, null=True)),
                ("institute", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "employment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PERMANENT", "Permanent"),
                            ("TEMPORARY", "Temporary"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "work_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ONSITE", "Onsite"),
                            ("REMOTE", "Remote"),
                            ("HYBRID", "Hybrid"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FULL_TIME", "Full-time"),
                            ("PART_TIME", "Part-time"),
                            ("INTERN", "Intern"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        blank=True,
                        choices=[("ACTIVE", "Active"), ("TERMINATED", "Terminated")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("hiring_date", models.DateField(blank=True, null=True)),
                ("probation_end_date", models.DateField(blank=True, null=True)),
                ("last_performance_review", models.DateField(blank=True, null=True)),
                (
                    "salary",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("balance_vacation", models.FloatField(default=0)),
                ("virtual_balance_vacation", models.FloatField(default=0)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.bimacorecountry",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical bima hr employee",
                "verbose_name_plural": "historical bima hr employees",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
