# Generated by Django 4.2 on 2023-04-13 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimahrskill',
            name='skillcategorys',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hr.skillcategory', verbose_name='skillcategorys_id'),
        ),
    ]
