# Generated by Django 4.2 on 2023-04-11 07:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bimacoretags'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BimaHrRefuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('raison', models.CharField(max_length=528)),
                ('date', models.DateTimeField()),
                ('id_manager', models.IntegerField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.bimahrapplicant')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.bimacoreposte')),
            ],
            options={
                'ordering': ['raison'],
                'permissions': [],
            },
        ),
    ]
