# Generated by Django 4.2 on 2023-04-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimahrcondidatposte',
            name='accepted_salary',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bimahrcondidatposte',
            name='expected_salary',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bimahrcondidatposte',
            name='proposed_salary',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
