# Generated by Django 5.0.6 on 2024-06-20 11:12

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
        ("hr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BimaHrCandidat",
            fields=[
                (
                    "bimahrperson_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="hr.bimahrperson",
                    ),
                ),
                ("availability_days", models.IntegerField()),
                ("message", models.TextField(max_length=256)),
            ],
            options={
                "ordering": ["first_name"],
                "permissions": [],
                "default_permissions": (),
            },
            bases=("hr.bimahrperson",),
        ),
        migrations.CreateModel(
            name="BimaHrVacancie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "work_location",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "seniority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("JUNIOR", "Junior"),
                            ("MID_LEVEL", "Mid-level"),
                            ("SENIOR", "Senior"),
                            ("EXECUTIVE", "Executive"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "work_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ONSITE", "Onsite"),
                            ("REMOTE", "Remote"),
                            ("HYBRID", "Hybrid"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FULL_TIME", "Full-time"),
                            ("PART_TIME", "Part-time"),
                            ("INTERN", "Intern"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("date_expiration", models.DateField(blank=True, null=True)),
                ("date_start_vacancie", models.DateField(blank=True, null=True)),
                (
                    "number_of_positions",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                ("published_date", models.DateTimeField(auto_now_add=True)),
                (
                    "position_status",
                    models.CharField(
                        blank=True,
                        choices=[("ACTIVE", "Active"), ("Closed", "CLOSED")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.bimacoredepartment",
                    ),
                ),
                (
                    "job_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hr.bimahrjobcategory",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manager",
                        to="hr.bimahremployee",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
                "permissions": [],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="BimaHrCandidatVacancie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "expected_salary",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                (
                    "proposed_salary",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                (
                    "accepted_salary",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("comments", models.TextField(max_length=256)),
                (
                    "candidat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.bimahrcandidat",
                    ),
                ),
                (
                    "vacancie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.bimahrvacancie",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="bimahrcandidat",
            name="candidat_vacancie",
            field=models.ManyToManyField(
                through="hr.BimaHrCandidatVacancie", to="hr.bimahrvacancie"
            ),
        ),
        migrations.CreateModel(
            name="HistoricalBimaHrCandidat",
            fields=[
                (
                    "bimahrperson_ptr",
                    models.ForeignKey(
                        auto_created=True,
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        related_name="+",
                        to="hr.bimahrperson",
                    ),
                ),
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("updated", models.DateTimeField(blank=True, editable=False)),
                (
                    "unique_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=32, null=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("MALE", "Male"), ("FEMALE", "Female")], max_length=16
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SINGLE", "Single"),
                            ("MARRIED", "Married"),
                            ("DIVORCED", "Divorced"),
                            ("WIDOWED", "Widowed"),
                            ("SEPARATED", "Separated"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("num_children", models.IntegerField(blank=True, default=0, null=True)),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(max_length=64)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "place_of_birth",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("nationality", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "identity_card_number",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                (
                    "second_phone_number",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "education_level",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "latest_degree",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("latest_degree_date", models.DateField(blank=True, null=True)),
                ("institute", models.CharField(blank=True, max_length=128, null=True)),
                ("availability_days", models.IntegerField()),
                ("message", models.TextField(max_length=256)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.bimacorecountry",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical bima hr candidat",
                "verbose_name_plural": "historical bima hr candidats",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
