# Generated by Django 4.2 on 2023-04-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimahrskill',
            name='applicant',
            field=models.ManyToManyField(blank=True, related_name='skill_condidat', to='hr.bimahrapplicant'),
        ),
    ]
