# Generated by Django 4.2.3 on 2023-09-25 13:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_remove_bimacorepost_department_and_more"),
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BimaHrJobCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="hr.bimahrjobcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["name"],
                "permissions": [],
            },
        ),
        migrations.CreateModel(
            name="BimaHrPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "unique_id",
                    models.CharField(blank=True, max_length=32, null=True, unique=True),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("MALE", "Male"), ("FEMALE", "Female")], max_length=16
                    ),
                ),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(max_length=64)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "place_of_birth",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("nationality", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "identity_card_number",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                (
                    "second_phone_number",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "education_level",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "latest_degree",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("latest_degree_date", models.DateField(blank=True, null=True)),
                ("institute", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.bimacorecountry",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BimaHrPersonExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("company_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("date_begin", models.DateField()),
                ("date_end", models.DateField(blank=True, null=True)),
                ("is_current_position", models.BooleanField(default=False)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="hr.bimahrperson",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BimaHrPersonSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.bimahrperson",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BimaHrPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "work_location",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "seniority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("JUNIOR", "Junior"),
                            ("MID_LEVEL", "Mid-level"),
                            ("SENIOR", "Senior"),
                            ("EXECUTIVE", "Executive"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("requirements", models.TextField(blank=True, null=True)),
                ("responsibilities", models.TextField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.bimacoredepartment",
                    ),
                ),
                (
                    "job_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hr.bimahrjobcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
                "permissions": [],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="BimaHrSkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="hr.bimahrskillcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["name"],
                "permissions": [],
            },
        ),
        migrations.RemoveField(
            model_name="bimahractivity",
            name="applicant",
        ),
        migrations.RemoveField(
            model_name="bimahractivity",
            name="type_id",
        ),
        migrations.RemoveField(
            model_name="bimahrapplicant",
            name="applicant_posts",
        ),
        migrations.RemoveField(
            model_name="bimahrapplicant",
            name="company_id",
        ),
        migrations.RemoveField(
            model_name="bimahrapplicant",
            name="id_source_type",
        ),
        migrations.RemoveField(
            model_name="bimahrapplicant",
            name="steps",
        ),
        migrations.RemoveField(
            model_name="bimahrapplicantpost",
            name="applicant",
        ),
        migrations.RemoveField(
            model_name="bimahrapplicantpost",
            name="post",
        ),
        migrations.RemoveField(
            model_name="bimahrinterview",
            name="applicant",
        ),
        migrations.RemoveField(
            model_name="bimahrinterview",
            name="steps",
        ),
        migrations.RemoveField(
            model_name="bimahrrefuse",
            name="applicant",
        ),
        migrations.RemoveField(
            model_name="bimahrrefuse",
            name="poste",
        ),
        migrations.RemoveField(
            model_name="skillcategory",
            name="parent",
        ),
        migrations.DeleteModel(
            name="SkillLevel",
        ),
        migrations.RemoveField(
            model_name="bimahrskill",
            name="applicant",
        ),
        migrations.CreateModel(
            name="BimaHrEmployee",
            fields=[
                (
                    "bimahrperson_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="hr.bimahrperson",
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SINGLE", "Single"),
                            ("MARRIED", "Married"),
                            ("DIVORCED", "Divorced"),
                            ("WIDOWED", "Widowed"),
                            ("SEPARATED", "Separated"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("num_children", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("PERMANENT", "Permanent"),
                            ("TEMPORARY", "Temporary"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "work_mode",
                    models.CharField(
                        choices=[
                            ("ONSITE", "Onsite"),
                            ("REMOTE", "Remote"),
                            ("HYBRID", "Hybrid"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "Full-time"),
                            ("PART_TIME", "Part-time"),
                            ("INTERN", "Intern"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("TERMINATED", "Terminated")],
                        max_length=20,
                    ),
                ),
                ("probation_end_date", models.DateField(blank=True, null=True)),
                ("last_performance_review", models.DateField(blank=True, null=True)),
                (
                    "salary",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["first_name"],
                "permissions": [],
                "default_permissions": (),
            },
            bases=("hr.bimahrperson",),
        ),
        migrations.DeleteModel(
            name="BimaHrActivity",
        ),
        migrations.DeleteModel(
            name="BimaHrActivityType",
        ),
        migrations.DeleteModel(
            name="BimaHrApplicant",
        ),
        migrations.DeleteModel(
            name="BimaHrApplicantPost",
        ),
        migrations.DeleteModel(
            name="BimaHrInterview",
        ),
        migrations.DeleteModel(
            name="BimaHrInterviewStep",
        ),
        migrations.DeleteModel(
            name="BimaHrRefuse",
        ),
        migrations.AddField(
            model_name="bimahrpersonskill",
            name="skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hr.bimahrskill"
            ),
        ),
        migrations.AddField(
            model_name="bimahrskill",
            name="persons",
            field=models.ManyToManyField(
                through="hr.BimaHrPersonSkill", to="hr.bimahrperson"
            ),
        ),
        migrations.AlterField(
            model_name="bimahrskill",
            name="skill_categories",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hr.bimahrskillcategory"
            ),
        ),
        migrations.DeleteModel(
            name="SkillCategory",
        ),
        migrations.AddField(
            model_name="bimahrposition",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="directs",
                to="hr.bimahremployee",
            ),
        ),
        migrations.AddField(
            model_name="bimahremployee",
            name="position",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee",
                to="hr.bimahrposition",
            ),
        ),
    ]
