# Generated by Django 4.2 on 2023-04-14 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_bimahrcondidatposte_accepted_salary_and_more'),
        ('hr', '0002_alter_bimahrskill_applicant'),
    ]

    operations = [
    ]
