# Generated by Django 4.2 on 2023-04-11 10:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_bimacoreadress_bimacoreaddress'),
        ('hr', '0002_bimahrrefuse'),
    ]

    operations = [
        migrations.CreateModel(
            name='BimaHrCondidatPoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('expected_salary', models.FloatField()),
                ('proposed_salary', models.FloatField()),
                ('accepted_salary', models.FloatField()),
                ('date', models.DateTimeField()),
                ('id_candidat', models.ManyToManyField(related_name='condidat_postes', to='hr.bimahrapplicant')),
                ('id_poste', models.ManyToManyField(related_name='condidat_postes', to='core.bimacoreposte')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
