# Generated by Django 5.0.6 on 2024-08-02 13:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0002_bimahrquestioncategory_bimahrquestion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bimahrapplicantpost",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMPLETED", "Completed"),
                    ("EXPIRED", "Expired"),
                    ("PLANNED", "Planned"),
                    ("CANCELED", "Canceled"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bimahrinterview",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMPLETED", "Completed"),
                    ("EXPIRED", "Expired"),
                    ("PLANNED", "Planned"),
                    ("CANCELED", "Canceled"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="BimaHrEmployeeinterviewer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.bimahremployee",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BimaHrInterviewQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("question", models.TextField()),
                ("response", models.TextField(blank=True)),
                (
                    "video_path",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/videos/"
                    ),
                ),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.bimahrinterview",
                    ),
                ),
            ],
            options={
                "permissions": [],
            },
        ),
        migrations.CreateModel(
            name="BimaHrTechnicalInterview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=256)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_datetime", models.DateTimeField(blank=True, null=True)),
                ("end_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "interview_mode",
                    models.CharField(
                        blank=True,
                        choices=[("ONLINE", "Online"), ("PHYSICAL", "Physical")],
                        max_length=64,
                        null=True,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("COMPLETED", "Completed"),
                            ("EXPIRED", "Expired"),
                            ("PLANNED", "Planned"),
                            ("CANCELED", "Canceled"),
                        ],
                        max_length=64,
                        null=True,
                    ),
                ),
                ("link_interview", models.URLField(blank=True, null=True)),
                ("record_path", models.URLField(blank=True, max_length=256, null=True)),
                ("id_event", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "candidat",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.bimahrcandidat",
                    ),
                ),
                (
                    "interview_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hr.bimahrinterviewstep",
                    ),
                ),
                (
                    "interviewers",
                    models.ManyToManyField(
                        through="hr.BimaHrEmployeeinterviewer", to="hr.bimahremployee"
                    ),
                ),
                (
                    "vacancie",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.bimahrvacancie",
                    ),
                ),
            ],
            options={
                "permissions": [],
            },
        ),
        migrations.AddField(
            model_name="bimahremployeeinterviewer",
            name="technical_interview",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="hr.bimahrtechnicalinterview",
            ),
        ),
    ]
