# Generated by Django 5.0.6 on 2024-06-20 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0002_bimahrcandidat_bimahrvacancie_bimahrcandidatvacancie_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bimahroffre",
            name="title",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hr.bimahrvacancie",
            ),
        ),
    ]
