# Generated by Django 4.2 on 2023-04-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_bimahrcondidatposte'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='id_candidat',
            field=models.ManyToManyField(related_name='skill_condidat', to='hr.bimahrapplicant'),
        ),
    ]
