# Generated by Django 4.2.3 on 2023-09-25 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0003_alter_bimahrskillcategory_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bimahrjobcategory",
            options={"ordering": ["name"], "permissions": []},
        ),
    ]
