# Generated by Django 5.0.6 on 2024-06-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0003_alter_bimahroffre_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bimahrvacancie",
            name="position_status",
            field=models.CharField(
                blank=True,
                choices=[("ACTIVE", "Active"), ("CLOSED", "Closed")],
                max_length=20,
                null=True,
            ),
        ),
    ]
