# Generated by Django 5.0.6 on 2024-08-05 10:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0003_alter_bimahrapplicantpost_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BimaHrTechnicalInterviewQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("question_te", models.TextField()),
                ("response_te", models.TextField(blank=True)),
                (
                    "interview_te",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.bimahrtechnicalinterview",
                    ),
                ),
            ],
            options={
                "permissions": [],
            },
        ),
    ]
