# Generated by Django 5.0.6 on 2024-06-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0004_bimahrquestion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bimahrquestion",
            name="question",
            field=models.TextField(unique=True),
        ),
    ]
