# Generated by Django 4.2 on 2023-04-11 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_skill_id_candidat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='id_candidat',
            new_name='applicant',
        ),
    ]
