# Generated by Django 4.2.3 on 2023-09-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0004_alter_bimahrjobcategory_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bimahrskill",
            old_name="skill_categories",
            new_name="skill_category",
        ),
        migrations.AddField(
            model_name="bimahrskill",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="bimahrskill",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
