# Generated by Django 4.2 on 2023-04-11 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_rename_id_candidat_skill_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bimahractivity',
            name='id_candidat',
        ),
        migrations.AddField(
            model_name='bimahractivity',
            name='applicant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hr.bimahrapplicant'),
            preserve_default=False,
        ),
    ]
