# Generated by Django 5.0.6 on 2024-06-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0005_bimahrcandidatvacancie_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bimahrcandidat",
            name="candidat_vacancie",
        ),
        migrations.AddField(
            model_name="bimahrvacancie",
            name="candidat_vacancie",
            field=models.ManyToManyField(
                through="hr.BimaHrCandidatVacancie", to="hr.bimahrvacancie"
            ),
        ),
    ]
