# Generated by Django 5.0.6 on 2024-06-20 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0005_alter_bimahrquestion_question"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bimahrquestion",
            old_name="question",
            new_name="name",
        ),
    ]
