# Generated by Django 4.2 on 2023-04-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_remove_bimahractivity_id_candidat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bimahractivity',
            name='applicant',
        ),
        migrations.AddField(
            model_name='bimahractivity',
            name='applicant',
            field=models.ManyToManyField(to='hr.bimahrapplicant'),
        ),
    ]
