# Generated by Django 5.0.6 on 2024-07-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0006_remove_bimahrcandidat_candidat_vacancie_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bimahroffre",
            name="activated_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bimahroffre",
            name="status",
            field=models.CharField(
                choices=[("Published", "Published"), ("Unpublished", "Unpublished")],
                default="unpublished",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bimahroffre",
            name="stopped_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
