# Generated by Django 5.0.6 on 2024-07-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0007_bimahroffre_activated_at_bimahroffre_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bimahroffre",
            name="status",
            field=models.CharField(
                choices=[("Published", "Published"), ("Unpublished", "Unpublished")],
                default="Unpublished",
                max_length=20,
            ),
        ),
    ]
