# Generated by Django 4.2.3 on 2023-09-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0007_historicalbimahremployee_historicalbimahrapplicant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bimahremployee",
            name="employment_status",
            field=models.CharField(
                blank=True,
                choices=[("ACTIVE", "Active"), ("TERMINATED", "Terminated")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bimahremployee",
            name="employment_type",
            field=models.CharField(
                blank=True,
                choices=[("PERMANENT", "Permanent"), ("TEMPORARY", "Temporary")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bimahremployee",
            name="job_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FULL_TIME", "Full-time"),
                    ("PART_TIME", "Part-time"),
                    ("INTERN", "Intern"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bimahremployee",
            name="work_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ONSITE", "Onsite"),
                    ("REMOTE", "Remote"),
                    ("HYBRID", "Hybrid"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbimahremployee",
            name="employment_status",
            field=models.CharField(
                blank=True,
                choices=[("ACTIVE", "Active"), ("TERMINATED", "Terminated")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbimahremployee",
            name="employment_type",
            field=models.CharField(
                blank=True,
                choices=[("PERMANENT", "Permanent"), ("TEMPORARY", "Temporary")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbimahremployee",
            name="job_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FULL_TIME", "Full-time"),
                    ("PART_TIME", "Part-time"),
                    ("INTERN", "Intern"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbimahremployee",
            name="work_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ONSITE", "Onsite"),
                    ("REMOTE", "Remote"),
                    ("HYBRID", "Hybrid"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
