# Generated by Django 4.2 on 2023-04-11 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_remove_bimahractivity_applicant_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skill',
            new_name='BimaHrSkill',
        ),
    ]
