# Generated by Django 4.2 on 2023-04-11 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_rename_skill_bimahrskill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bimahractivity',
            name='applicant',
        ),
        migrations.AddField(
            model_name='bimahractivity',
            name='applicant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hr.bimahrapplicant'),
            preserve_default=False,
        ),
    ]
