# Generated by Django 4.2.3 on 2023-09-26 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0008_alter_bimahremployee_employment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bimahremployee",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hr.bimahrposition",
            ),
        ),
    ]
