# Generated by Django 5.0.6 on 2024-07-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0008_alter_bimahroffre_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bimahroffre",
            name="salary",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="bimahrvacancie",
            name="candidat_vacancie",
            field=models.ManyToManyField(
                through="hr.BimaHrCandidatVacancie", to="hr.bimahrcandidat"
            ),
        ),
    ]
