# Generated by Django 5.0.6 on 2024-07-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0009_alter_bimahrvacancie_job_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bimahrvacancie",
            name="candidat_vacancie",
        ),
        migrations.AddField(
            model_name="bimahrvacancie",
            name="candidats",
            field=models.ManyToManyField(
                through="hr.BimaHrCandidatVacancie", to="hr.bimahrcandidat"
            ),
        ),
    ]
