# Generated by Django 5.0.6 on 2024-07-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0009_alter_bimahroffre_salary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bimahrvacancie",
            name="job_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FULL_TIME", "Full-time"),
                    ("PART_TIME", "Part-time"),
                    ("INTERN", "Intern"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bimahrvacancie",
            name="position_status",
            field=models.CharField(
                blank=True,
                choices=[("ACTIVE", "Active"), ("CLOSED", "Closed")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bimahrvacancie",
            name="work_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ONSITE", "Onsite"),
                    ("REMOTE", "Remote"),
                    ("HYBRID", "Hybrid"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
