# Generated by Django 4.2.3 on 2023-09-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0009_alter_bimahremployee_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="bimahremployee",
            name="hiring_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bimahrpersonexperience",
            name="position",
            field=models.CharField(default="PDG", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalbimahremployee",
            name="hiring_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
