# Generated by Django 5.0.6 on 2024-07-03 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0010_remove_bimahrvacancie_candidat_vacancie_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bimahrvacancie",
            old_name="candidats",
            new_name="candidat_vacancie",
        ),
    ]
