# Generated by Django 5.0.6 on 2024-07-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0011_rename_candidats_bimahrvacancie_candidat_vacancie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bimahroffre",
            name="salary",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
