# Generated by Django 4.2.3 on 2023-09-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0012_alter_bimahremployee_hiring_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bimahremployee",
            name="hiring_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bimahremployee",
            name="last_performance_review",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bimahremployee",
            name="probation_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bimahrperson",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bimahrperson",
            name="latest_degree_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalbimahrapplicant",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalbimahrapplicant",
            name="latest_degree_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalbimahremployee",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalbimahremployee",
            name="hiring_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalbimahremployee",
            name="last_performance_review",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalbimahremployee",
            name="latest_degree_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalbimahremployee",
            name="probation_end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
