# Generated by Django 4.2.3 on 2023-10-03 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0014_bimahremployee_user_historicalbimahremployee_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="bimahrvacation",
            name="request_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bimahrvacation",
            name="status_change_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
