# Generated by Django 5.0.6 on 2024-07-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0014_alter_bimahroffre_inclusive_contact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bimahrinterview",
            name="name",
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
