# Generated by Django 4.2.3 on 2023-10-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0016_alter_bimahrvacation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bimahrvacation",
            name="vacation_type",
            field=models.CharField(
                choices=[
                    ("ANNUAL", "Annual"),
                    ("SICK", "Sick"),
                    ("UNPAID", "Unpaid"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
