# Generated by Django 5.0.6 on 2024-07-10 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0016_bimahrquestioncategory_bimahrquestion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bimahrinterview",
            options={"ordering": ["-name"], "permissions": []},
        ),
        migrations.RenameField(
            model_name="bimahrinterview",
            old_name="refusal_date",
            new_name="scheduled_date",
        ),
        migrations.RemoveField(
            model_name="bimahrinterview",
            name="additional_comments",
        ),
        migrations.RemoveField(
            model_name="bimahrinterview",
            name="applicant_post",
        ),
        migrations.RemoveField(
            model_name="bimahrinterview",
            name="comments",
        ),
        migrations.RemoveField(
            model_name="bimahrinterview",
            name="date",
        ),
        migrations.RemoveField(
            model_name="bimahrinterview",
            name="interview_step",
        ),
        migrations.RemoveField(
            model_name="bimahrinterview",
            name="interviewer",
        ),
        migrations.RemoveField(
            model_name="bimahrinterview",
            name="note",
        ),
        migrations.RemoveField(
            model_name="bimahrinterview",
            name="refusal_reason",
        ),
        migrations.RemoveField(
            model_name="bimahrinterview",
            name="refused_by",
        ),
        migrations.AddField(
            model_name="bimahrinterview",
            name="candidat",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="hr.bimahrcandidat",
            ),
        ),
        migrations.AddField(
            model_name="bimahrinterview",
            name="due_date",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OneDay", "1 Day"),
                    ("TwoDay", "2 Day"),
                    ("ThreeDay", "3 Day"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bimahrinterview",
            name="estimated_time",
            field=models.CharField(
                blank=True,
                choices=[("t_1", "30 min"), ("t_2", "1 h"), ("t_3", "1h:30min")],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bimahrinterview",
            name="interview_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TECHNICAL", "Technical"),
                    ("HR", "Hr"),
                    ("INITIAL", "Initial"),
                ],
                default="Initail",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bimahrinterview",
            name="link_interview",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bimahrinterview",
            name="vacancie",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="hr.bimahrvacancie",
            ),
        ),
        migrations.AlterField(
            model_name="bimahrapplicantpost",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PASSED", "Passed"),
                    ("FAILED", "Failed"),
                    ("REFUSED", "Refused"),
                    ("PENDING", "Pending"),
                    ("IN_PROGRESS", "In Progress"),
                    ("Un_planned", "Unplanned"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bimahrinterview",
            name="name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="bimahrinterview",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PASSED", "Passed"),
                    ("FAILED", "Failed"),
                    ("REFUSED", "Refused"),
                    ("PENDING", "Pending"),
                    ("IN_PROGRESS", "In Progress"),
                    ("Un_planned", "Unplanned"),
                ],
                default="Unplanned",
                max_length=64,
                null=True,
            ),
        ),
    ]
