# Generated by Django 5.0.6 on 2024-07-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0016_alter_bimahrinterview_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bimahrinterview",
            name="comments",
            field=models.TextField(blank=True),
        ),
    ]
