# Generated by Django 5.0.6 on 2024-07-12 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0017_bimahrinterview_comments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bimahrquestion",
            old_name="name",
            new_name="question",
        ),
    ]
