# Generated by Django 5.0.6 on 2024-07-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0017_alter_bimahrinterview_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bimahrapplicantpost",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMPLETED", "Completed"),
                    ("EXPIRED", "Expired"),
                    ("PLANNED", "Planned"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bimahrinterview",
            name="due_date",
            field=models.CharField(
                blank=True,
                choices=[
                    ("One_Day", "1 Day"),
                    ("Two_Day", "2 Day"),
                    ("Three_Day", "3 Day"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bimahrinterview",
            name="estimated_time",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Half_hour", "30 min"),
                    ("One_hour", "1 h"),
                    ("One_hour_half", "1h:30min"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bimahrinterview",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMPLETED", "Completed"),
                    ("EXPIRED", "Expired"),
                    ("PLANNED", "Planned"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
