# Generated by Django 4.2.3 on 2023-10-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0018_bimahrcontract_historicalbimahrcontract_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bimahrcontract",
            name="exit_notice_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bimahrcontract",
            name="probation_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalbimahrcontract",
            name="exit_notice_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalbimahrcontract",
            name="probation_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bimahrcontract",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("SUSPENDED", "Suspended"),
                    ("EXPIRED", "Expired"),
                    ("TERMINATED", "Terminated"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="bimahrcontractamendment",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("SUSPENDED", "Suspended"),
                    ("EXPIRED", "Expired"),
                    ("TERMINATED", "Terminated"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbimahrcontract",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("SUSPENDED", "Suspended"),
                    ("EXPIRED", "Expired"),
                    ("TERMINATED", "Terminated"),
                ]
            ),
        ),
    ]
