# Generated by Django 5.0.6 on 2024-07-10 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0018_alter_bimahrapplicantpost_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bimahrinterview",
            name="interview_type",
        ),
        migrations.AddField(
            model_name="bimahrinterview",
            name="interview_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="hr.bimahrinterviewstep",
            ),
        ),
        migrations.AlterField(
            model_name="bimahrinterviewstep",
            name="interview_type",
            field=models.CharField(
                blank=True,
                choices=[("TECHNICAL", "Technical"), ("HR", "Hr")],
                max_length=100,
                null=True,
            ),
        ),
    ]
