# Generated by Django 5.0.6 on 2024-07-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0018_rename_name_bimahrquestion_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="bimahrinterviewquestion",
            name="video_path",
            field=models.FileField(blank=True, null=True, upload_to="uploads/videos/"),
        ),
        migrations.AlterField(
            model_name="bimahrinterview",
            name="estimated_time",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Half_hour", "30 min"),
                    ("One_hour", "1 h"),
                    ("One_hour_half", "1h:30min"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
