# Generated by Django 5.0.6 on 2024-08-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0019_bimahrinterviewquestion_video_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bimahrapplicantpost",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMPLETED", "Completed"),
                    ("EXPIRED", "Expired"),
                    ("PLANNED", "Planned"),
                    ("CANCELED", "Canceled"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bimahrinterview",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMPLETED", "Completed"),
                    ("EXPIRED", "Expired"),
                    ("PLANNED", "Planned"),
                    ("CANCELED", "Canceled"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
