# Generated by Django 4.2.3 on 2023-10-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0020_alter_bimahrvacation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="bimahrcontractamendment",
            name="new_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bimahrcontractamendment",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
