# Generated by Django 5.0.6 on 2024-08-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0021_bimahremployeeinterviewer_bimahrtechnicalinterview_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bimahrtechnicalinterview",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="bimahrtechnicalinterview",
            name="start_date",
        ),
        migrations.AddField(
            model_name="bimahrtechnicalinterview",
            name="end_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bimahrtechnicalinterview",
            name="start_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
