# Generated by Django 4.2.3 on 2023-10-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0021_bimahrcontractamendment_new_start_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bimahrcontract",
            name="suspension_reason_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SICK_LEAVE", "Sick Leave"),
                    ("MATERNITY_LEAVE", "Maternity Leave"),
                    ("PROFESSIONAL_TRAINING", "Professional Training"),
                    ("WORK_ACCIDENT", "Work Accident"),
                    ("DISCIPLINARY_SUSPENSION", "Disciplinary Suspension"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bimahrcontract",
            name="termination_reason_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MUTUAL_TERMINATION", "Mutual Termination"),
                    ("DISMISSAL", "Dismissal"),
                    ("RESIGNATION", "Resignation"),
                    ("CONTRACT_TERMINATION", "Contract Termination"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalbimahrcontract",
            name="suspension_reason_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SICK_LEAVE", "Sick Leave"),
                    ("MATERNITY_LEAVE", "Maternity Leave"),
                    ("PROFESSIONAL_TRAINING", "Professional Training"),
                    ("WORK_ACCIDENT", "Work Accident"),
                    ("DISCIPLINARY_SUSPENSION", "Disciplinary Suspension"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalbimahrcontract",
            name="termination_reason_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MUTUAL_TERMINATION", "Mutual Termination"),
                    ("DISMISSAL", "Dismissal"),
                    ("RESIGNATION", "Resignation"),
                    ("CONTRACT_TERMINATION", "Contract Termination"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bimahrcontractamendment",
            name="other_changes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
