# Generated by Django 5.0.6 on 2024-08-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0023_rename_interviewer_bimahrtechnicalinterview_interviewers"),
    ]

    operations = [
        migrations.AddField(
            model_name="bimahrtechnicalinterview",
            name="id_event",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
