# Generated by Django 5.0.6 on 2024-08-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0024_bimahrtechnicalinterview_id_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bimahroffre",
            name="inclusive_contact",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="bimahroffre",
            name="inclusive_education",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="bimahroffre",
            name="seniority",
            field=models.CharField(
                blank=True,
                choices=[
                    ("JUNIOR", "Junior"),
                    ("MID_LEVEL", "Mid-level"),
                    ("SENIOR", "Senior"),
                    ("EXECUTIVE", "Executive"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bimahroffre",
            name="work_location",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
