# Generated by Django 4.2.3 on 2023-10-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0025_bimahractivity_bimahractivitytype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bimahractivity",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bimahractivitytype",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalbimahractivity",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
