version: '3.8'

services:
  rabbitmq:
    container_name: bima360_rabbitmq
    build:
      context: .
    networks:
      - bima360_network-external
    restart: always
networks:
  bima360_network-external:
    external:
      name: bima360-network
