version: '3'

services:
  rabbitmq:
    container_name: bima360_rabbitmq
    build:
      context: .
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - bima360_network-external
    restart: always
networks:
  bima360_network-external:
    external:
      name: bima360-network
