# Generated by Django 4.2.2 on 2023-06-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_password_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_password_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
