# Generated by Django 4.2.2 on 2023-07-06 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_approved_at_user_approved_by_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'default_permissions': (), 'ordering': ['name'], 'permissions': []},
        ),
    ]
