# Generated by Django 4.2.2 on 2023-07-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_is_password_change_when_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reason_declined',
            field=models.TextField(blank=True, null=True),
        ),
    ]
