# Generated by Django 4.2.3 on 2023-09-01 10:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("user", "0007_user_reason_declined"),
    ]

    operations = [
        migrations.CreateModel(
            name="BimaUserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "permissions",
                    models.ManyToManyField(blank=True, to="auth.permission"),
                ),
            ],
            options={
                "ordering": ["name"],
                "permissions": [],
                "default_permissions": (),
            },
        ),
    ]
