# Generated by Django 4.2.3 on 2024-05-21 10:01

import common.validators.file_validators
import core.document.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="BimaCoreAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=28)),
                ("street", models.CharField(max_length=256)),
                ("street2", models.CharField(blank=True, max_length=256, null=True)),
                ("zip", models.CharField(max_length=28)),
                ("city", models.CharField(max_length=128)),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=256, null=True),
                ),
                ("can_send_bill", models.BooleanField(blank=True, null=True)),
                ("can_deliver", models.BooleanField(blank=True, null=True)),
                ("latitude", models.CharField(blank=True, max_length=256, null=True)),
                ("longitude", models.CharField(blank=True, max_length=256, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("parent_id", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["number"],
                "permissions": [],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="BimaCoreBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("bic", models.CharField(max_length=16, unique=True)),
            ],
            options={
                "ordering": ["name"],
                "permissions": [],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="BimaCoreContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="Si Ala", max_length=256)),
                ("position", models.CharField(blank=True, max_length=256, null=True)),
                ("department", models.CharField(blank=True, max_length=256, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("fax", models.CharField(blank=True, max_length=128)),
                ("mobile", models.CharField(blank=True, max_length=128)),
                ("phone", models.CharField(blank=True, max_length=128)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("MALE", "Male"), ("FEMALE", "Female")],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("parent_id", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["name"],
                "permissions": [],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="BimaCoreCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=256, null=True, unique=True
                    ),
                ),
                (
                    "iso3",
                    models.CharField(
                        blank=True, max_length=256, null=True, unique=True
                    ),
                ),
                (
                    "iso2",
                    models.CharField(
                        blank=True, max_length=256, null=True, unique=True
                    ),
                ),
                ("phone_code", models.CharField(blank=True, null=True)),
                ("capital", models.CharField(blank=True, null=True)),
                (
                    "address_format",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("vat_label", models.CharField(blank=True, max_length=64, null=True)),
                ("zip_required", models.BooleanField(null=True)),
            ],
            options={
                "ordering": ["-name"],
                "permissions": [],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="BimaCoreCurrency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                (
                    "symbol",
                    models.CharField(blank=True, max_length=16, null=True, unique=True),
                ),
                ("decimal_places", models.PositiveIntegerField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "currency_unit_label",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "currency_subunit_label",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
            ],
            options={
                "ordering": ["name"],
                "permissions": [],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="BimaCoreDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("manager", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
                "permissions": [],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="BimaCoreDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "document_name",
                    models.CharField(default="new_document", max_length=256),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_content_type",
                    models.CharField(
                        default="application/octet-stream", max_length=255
                    ),
                ),
                ("file_extension", models.CharField(max_length=16)),
                ("date_file", models.DateTimeField(auto_now_add=True)),
                (
                    "file_path",
                    models.FileField(
                        upload_to=core.document.models.BimaCoreDocument.document_file_path,
                        validators=[
                            common.validators.file_validators.validate_file_size,
                            common.validators.file_validators.validate_file_extension,
                        ],
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("PARTNER_PICTURE", "PARTNER_PICTURE"),
                            ("PARTNER_PRIVATE_DOCUMENT", "PARTNER_PRIVATE_DOCUMENT"),
                            ("PARTNER_CIRET_DOCUMENT", "PARTNER_CIRET_DOCUMENT"),
                            ("COMPANY_LOGO", "Logo"),
                            ("COMPANY_DOCUMENT", "Documents"),
                            ("EMPLOYEE_CV", "EMPLOYEE_CV"),
                            ("EMPLOYEE_RESUME", "EMPLOYEE_RESUME"),
                            ("EMPLOYEE_DRIVER_LICENCE", "EMPLOYEE_DRIVER_LICENCE"),
                            ("EMPLOYEE_PICTURE", "EMPLOYEE_PICTURE"),
                            ("EMPLOYEE_CONTRACT", "EMPLOYEE_CONTRACT"),
                            ("USER_PROFILE_PICTURE", "USER_PROFILE_PICTURE"),
                            ("USER_OTHER", "USER_OTHER"),
                            (
                                "SELLER_PURCHASE_QUOTE_DOCUMENT",
                                "SELLER_PURCHASE_QUOTE_DOCUMENT",
                            ),
                            (
                                "SELLER_PURCHASE_ORDER_DOCUMENT",
                                "SELLER_PURCHASE_ORDER_DOCUMENT",
                            ),
                            (
                                "SELLER_PURCHASE_INVOICE_DOCUMENT",
                                "SELLER_PURCHASE_INVOICE_DOCUMENT",
                            ),
                            ("CONTRACT_MAIN", "CONTRACT_MAIN"),
                            ("CONTRACT_RENEW", "CONTRACT_RENEW"),
                            ("CONTRACT_AMENDMENT", "CONTRACT_AMENDMENT"),
                            ("RESIGNATION", "RESIGNATION"),
                        ],
                        max_length=128,
                    ),
                ),
                ("is_favorite", models.BooleanField(blank=True, default=False)),
                ("parent_id", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["-created", "document_name"],
                "permissions": [],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="BimaCoreEntityTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("id_manager", models.IntegerField(blank=True, null=True)),
                (
                    "order",
                    models.PositiveIntegerField(blank=True, default=1, null=True),
                ),
                ("parent_id", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["-created"],
                "permissions": [],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="BimaCoreNotificationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("active", models.BooleanField(default=True)),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=128, null=True, unique=True
                    ),
                ),
                ("is_system", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["name"],
                "permissions": [],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="BimaCoreSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
                "permissions": [],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="GlobalPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="BimaCoreTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("color", models.CharField(blank=True, max_length=6, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="core.bimacoretag",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "permissions": [],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="BimaCoreState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("code", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.bimacorecountry",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "permissions": [],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="BimaCoreNotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.bimacompany",
                    ),
                ),
                (
                    "notification_type",
                    models.OneToOneField(
                        error_messages={
                            "unique": "A template with this notification type already exists."
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.bimacorenotificationtype",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "permissions": [],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="BimaCoreNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("receivers_email", models.JSONField(blank=True, null=True)),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("attachments", models.JSONField(blank=True, null=True)),
                ("date_sent", models.DateTimeField(auto_now_add=True)),
                ("parent_id", models.PositiveIntegerField()),
                (
                    "notification_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.bimacorenotificationtype",
                    ),
                ),
                (
                    "parent_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_sent"],
                "permissions": [],
                "default_permissions": (),
            },
        ),
    ]
