# Generated by Django 4.2.3 on 2024-05-21 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="bimacorenotification",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sent_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bimacoreentitytag",
            name="parent_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="bimacoreentitytag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.bimacoretag"
            ),
        ),
        migrations.AddField(
            model_name="bimacoredocument",
            name="parent_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="bimacoredepartment",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="core.bimacoredepartment",
            ),
        ),
        migrations.AddField(
            model_name="bimacorecountry",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.bimacorecurrency"
            ),
        ),
        migrations.AddField(
            model_name="bimacorecontact",
            name="parent_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="bimacoreaddress",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.bimacorecountry"
            ),
        ),
        migrations.AddField(
            model_name="bimacoreaddress",
            name="parent_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="bimacoreaddress",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.bimacorestate"
            ),
        ),
    ]
