# Generated by Django 4.2 on 2023-04-11 07:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BimaCoreTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('id_manager', models.IntegerField()),
                ('parent_id', models.PositiveIntegerField()),
                ('parent_type', models.ForeignKey(limit_choices_to={'app_label__in': ['messages', 'staticfiles', 'rest_framework', 'drf_spectacular', 'core', 'user', 'hr']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['name'],
                'permissions': [],
            },
        ),
    ]
