# Generated by Django 4.2 on 2023-04-13 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bimacoreaddress',
            old_name='country',
            new_name='country1',
        ),
        migrations.RemoveField(
            model_name='bimacoreaddress',
            name='state',
        ),
        migrations.AddField(
            model_name='bimacoreaddress',
            name='state1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.bimacorestate'),
            preserve_default=False,
        ),
    ]
