# Generated by Django 4.2.1 on 2023-05-09 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimacoreaddress',
            name='parent_type',
            field=models.ForeignKey(limit_choices_to={'app_label__in': ['messages', 'staticfiles', 'rest_framework', 'drf_spectacular', 'core', 'user', 'hr', 'company']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='bimacorecontact',
            name='parent_type',
            field=models.ForeignKey(limit_choices_to={'app_label__in': ['messages', 'staticfiles', 'rest_framework', 'drf_spectacular', 'core', 'user', 'hr', 'company']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='bimacoredocument',
            name='parent_type',
            field=models.ForeignKey(limit_choices_to={'app_label__in': ['messages', 'staticfiles', 'rest_framework', 'drf_spectacular', 'core', 'user', 'hr', 'company']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='bimacoretags',
            name='parent_type',
            field=models.ForeignKey(limit_choices_to={'app_label__in': ['messages', 'staticfiles', 'rest_framework', 'drf_spectacular', 'core', 'user', 'hr', 'company']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
