# Generated by Django 4.2.1 on 2023-05-18 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bimacorepost',
            old_name='department_id',
            new_name='department',
        ),
    ]
