# Generated by Django 4.2 on 2023-04-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimacoredepartment',
            name='manager_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
