# Generated by Django 4.2 on 2023-04-11 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_bimacoretags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BimaCoreAdress',
            new_name='BimaCoreAddress',
        ),
    ]
