<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-06-25 14:15
=======
# Generated by Django 5.0.6 on 2024-07-05 16:46
>>>>>>> origin/ma-branch

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bimacoredocument",
            name="file_type",
            field=models.CharField(
                choices=[
<<<<<<< HEAD
                    ("CANDIDAT_CV", "CANDIDAT_CV"),
                    ("CANDIDAT_RESUME", "CANDIDAT_RESUME"),
                    ("CANDIDAT_PICTURE", "CANDIDAT_PICTURE"),
                    ("CANDIDAT_OTHER", "CANDIDAT_OTHER"),
=======
>>>>>>> origin/ma-branch
                    ("PARTNER_PICTURE", "PARTNER_PICTURE"),
                    ("PARTNER_PRIVATE_DOCUMENT", "PARTNER_PRIVATE_DOCUMENT"),
                    ("PARTNER_CIRET_DOCUMENT", "PARTNER_CIRET_DOCUMENT"),
                    ("COMPANY_LOGO", "Logo"),
                    ("COMPANY_DOCUMENT", "Documents"),
                    ("EMPLOYEE_CV", "EMPLOYEE_CV"),
                    ("EMPLOYEE_RESUME", "EMPLOYEE_RESUME"),
                    ("EMPLOYEE_DRIVER_LICENCE", "EMPLOYEE_DRIVER_LICENCE"),
                    ("EMPLOYEE_PICTURE", "EMPLOYEE_PICTURE"),
                    ("EMPLOYEE_CONTRACT", "EMPLOYEE_CONTRACT"),
                    ("USER_PROFILE_PICTURE", "USER_PROFILE_PICTURE"),
                    ("USER_OTHER", "USER_OTHER"),
                    (
                        "SELLER_PURCHASE_QUOTE_DOCUMENT",
                        "SELLER_PURCHASE_QUOTE_DOCUMENT",
                    ),
                    (
                        "SELLER_PURCHASE_ORDER_DOCUMENT",
                        "SELLER_PURCHASE_ORDER_DOCUMENT",
                    ),
                    (
                        "SELLER_PURCHASE_INVOICE_DOCUMENT",
                        "SELLER_PURCHASE_INVOICE_DOCUMENT",
                    ),
                    ("CONTRACT_MAIN", "CONTRACT_MAIN"),
                    ("CONTRACT_RENEW", "CONTRACT_RENEW"),
                    ("CONTRACT_AMENDMENT", "CONTRACT_AMENDMENT"),
                    ("RESIGNATION", "RESIGNATION"),
<<<<<<< HEAD
=======
                    ("CANDIDAT_CV", "CANDIDAT_CV"),
                    ("CANDIDAT_RESUME", "CANDIDAT_RESUME"),
                    ("CANDIDAT_PICTURE", "CANDIDAT_PICTURE"),
                    ("CANDIDAT_OTHER", "CANDIDAT_OTHER"),
>>>>>>> origin/ma-branch
                ],
                max_length=128,
            ),
        ),
    ]
