# Generated by Django 4.2.1 on 2023-05-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_department_id_bimacorepost_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bimacorepost',
            old_name='department',
            new_name='department_id',
        ),
    ]
