# Generated by Django 4.2 on 2023-04-13 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_country_bimacoreaddress_country1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bimacoreaddress',
            old_name='country1',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='bimacoreaddress',
            old_name='state1',
            new_name='state',
        ),
    ]
