# Generated by Django 4.2.1 on 2023-05-18 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_department_bimacorepost_department_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bimacorepost',
            old_name='department_id',
            new_name='department',
        ),
    ]
