# Generated by Django 4.2 on 2023-04-11 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_rename_bimacoreadress_bimacoreaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bimacoredocument',
            name='content_type',
        ),
        migrations.AddField(
            model_name='bimacoredocument',
            name='parent_type',
            field=models.ForeignKey(default=1, limit_choices_to={'app_label__in': ['messages', 'staticfiles', 'rest_framework', 'drf_spectacular', 'core', 'user', 'hr']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
    ]
