# Generated by Django 4.2.1 on 2023-05-22 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_department_id_bimacorepost_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bimacoredepartment',
            old_name='parent_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='bimacoredepartment',
            old_name='manager_id',
            new_name='manager',
        ),
    ]
