# Generated by Django 4.2.1 on 2023-05-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_parent_id_bimacoredepartment_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimacorebank',
            name='bic',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='bimacoredepartment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
