# Generated by Django 4.2.1 on 2023-05-30 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0007_alter_bimacoreaddress_parent_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimacoreaddress',
            name='parent_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['logentry', 'permission', 'group', 'contenttype', 'session', 'logentry', 'bimacorecurrency', 'bimacorecountry', 'bimacorestate', 'user', 'bimacompany']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
