# Generated by Django 4.2.1 on 2023-05-30 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0008_alter_bimacoreaddress_parent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimacoreaddress',
            name='parent_type',
            field=models.ForeignKey(limit_choices_to={'app_label__in': ['messages', 'staticfiles', 'debug_toolbar', 'corsheaders', 'rest_framework', 'drf_spectacular', 'logging', 'core', 'user', 'hr', 'company', 'erp']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
