# Generated by Django 4.2.1 on 2023-05-31 08:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0009_alter_bimacoreaddress_parent_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BimaCoreEntityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_manager', models.IntegerField(blank=True, null=True)),
                ('parent_id', models.PositiveIntegerField()),
                ('parent_type', models.ForeignKey(limit_choices_to={'app_label__in': ['messages', 'staticfiles', 'debug_toolbar', 'corsheaders', 'rest_framework', 'drf_spectacular', 'logging', 'core', 'user', 'hr', 'company', 'erp']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['name'],
                'permissions': [],
            },
        ),
        migrations.CreateModel(
            name='BimaCoreTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['name'],
                'permissions': [],
            },
        ),
        migrations.AlterModelOptions(
            name='bimacoredocument',
            options={'ordering': ['-date_file', 'file_name'], 'permissions': []},
        ),
        migrations.AddField(
            model_name='bimacoreaddress',
            name='can_deliver',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bimacoreaddress',
            name='can_send_bill',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bimacoreaddress',
            name='contact_email',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='bimacoreaddress',
            name='contact_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='bimacoreaddress',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='bimacoreaddress',
            name='latitude',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='bimacoreaddress',
            name='longitude',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='bimacoreaddress',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bimacorecontact',
            name='department',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='bimacorecontact',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=32),
        ),
        migrations.AddField(
            model_name='bimacorecontact',
            name='name',
            field=models.CharField(default='Si Ala', max_length=256),
        ),
        migrations.AddField(
            model_name='bimacorecontact',
            name='position',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='bimacorecontact',
            name='fax',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='bimacorecontact',
            name='mobile',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='bimacorecontact',
            name='phone',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='bimacoredocument',
            name='file_type',
            field=models.CharField(choices=[('PARTNER_PICTURE', 'PARTNER_PICTURE'), ('PARTNER_PRIVATE_DOCUMENT', 'PARTNER_PRIVATE_DOCUMENT'), ('PARTNER_CIRET_DOCUMENT', 'PARTNER_CIRET_DOCUMENT')], max_length=100),
        ),
        migrations.DeleteModel(
            name='BimaCoreTags',
        ),
        migrations.AddField(
            model_name='bimacoreentitytag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.bimacoretag'),
        ),
    ]
