# Generated by Django 4.2.1 on 2023-06-02 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0010_bimacoreentitytag_bimacoretag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bimacoredocument',
            options={'ordering': ['-created', 'file_name'], 'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='bimacoreentitytag',
            options={'ordering': ['-created'], 'permissions': []},
        ),
        migrations.AlterField(
            model_name='bimacoreaddress',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='bimacoreaddress',
            name='parent_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='bimacorecontact',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=32),
        ),
        migrations.AlterField(
            model_name='bimacorecontact',
            name='parent_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
