# Generated by Django 4.2.1 on 2023-06-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_bimacoredocument_parent_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimacoredocument',
            name='file_content_type',
            field=models.CharField(default='application/octet-stream', max_length=255),
        ),
        migrations.AlterField(
            model_name='bimacoredocument',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bimacoredocument',
            name='document_name',
            field=models.CharField(default='new_document', max_length=256),
        ),
        migrations.AlterField(
            model_name='bimacoredocument',
            name='file_extension',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='bimacoredocument',
            name='file_type',
            field=models.CharField(choices=[('PARTNER_PICTURE', 'PARTNER_PICTURE'), ('PARTNER_PRIVATE_DOCUMENT', 'PARTNER_PRIVATE_DOCUMENT'), ('PARTNER_CIRET_DOCUMENT', 'PARTNER_CIRET_DOCUMENT')], max_length=128),
        ),
    ]
