# Generated by Django 4.2.1 on 2023-06-08 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_bimacoredocument_file_content_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bimacoredocument',
            options={'ordering': ['-created', 'document_name'], 'permissions': []},
        ),
        migrations.RemoveField(
            model_name='bimacorecountry',
            name='address_view_id',
        ),
        migrations.RemoveField(
            model_name='bimacorecountry',
            name='name_position',
        ),
        migrations.RemoveField(
            model_name='bimacorecountry',
            name='state_required',
        ),
        migrations.RemoveField(
            model_name='bimacorecurrency',
            name='position',
        ),
        migrations.RemoveField(
            model_name='bimacorecurrency',
            name='rounding',
        ),
    ]
