# Generated by Django 4.2.1 on 2023-06-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_bimacoredocument_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimacorebank',
            name='bic',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='bimacorebank',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
