# Generated by Django 4.2.1 on 2023-06-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_bimacorebank_bic_alter_bimacorebank_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimacorecountry',
            name='code',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bimacorecurrency',
            name='symbol',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
