# Generated by Django 4.2.1 on 2023-06-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_bimacorecountry_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimacoreentitytag',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
