# Generated by Django 4.2.2 on 2023-06-21 13:22

import common.validators.file_validators
import core.document.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_bimacorecountry_capital_bimacorecountry_iso2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bimacorecontact',
            options={'ordering': ['name'], 'permissions': []},
        ),
        migrations.AlterField(
            model_name='bimacorecontact',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='bimacoredocument',
            name='file_path',
            field=models.FileField(upload_to=core.document.models.BimaCoreDocument.document_file_path, validators=[common.validators.file_validators.validate_file_size, common.validators.file_validators.validate_file_extension]),
        ),
    ]
