# Generated by Django 4.2.2 on 2023-06-26 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_globalpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimacoretag',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.bimacoretag'),
        ),
    ]
