# Generated by Django 4.2.2 on 2023-07-04 07:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_bimacoretag_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BimaCoreCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
                'permissions': [],
            },
        ),
        migrations.AlterModelOptions(
            name='bimacorecountry',
            options={'ordering': ['-name'], 'permissions': []},
        ),
        migrations.AddField(
            model_name='bimacoretag',
            name='color',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='bimacorecurrency',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
