# Generated by Django 4.2.2 on 2023-07-06 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_bimacoredocument_is_favorite_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bimacoreaddress',
            options={'default_permissions': (), 'ordering': ['number'], 'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='bimacorebank',
            options={'default_permissions': (), 'ordering': ['name'], 'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='bimacorecash',
            options={'default_permissions': (), 'ordering': ['id'], 'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='bimacorecontact',
            options={'default_permissions': (), 'ordering': ['name'], 'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='bimacorecountry',
            options={'default_permissions': (), 'ordering': ['-name'], 'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='bimacorecurrency',
            options={'default_permissions': (), 'ordering': ['name'], 'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='bimacoredepartment',
            options={'default_permissions': (), 'ordering': ['name'], 'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='bimacoredocument',
            options={'default_permissions': (), 'ordering': ['-created', 'document_name'], 'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='bimacoreentitytag',
            options={'default_permissions': (), 'ordering': ['-created'], 'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='bimacorepost',
            options={'default_permissions': (), 'ordering': ['name'], 'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='bimacoresource',
            options={'default_permissions': (), 'ordering': ['name'], 'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='bimacorestate',
            options={'default_permissions': (), 'ordering': ['name'], 'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='bimacoretag',
            options={'default_permissions': (), 'ordering': ['name'], 'permissions': []},
        ),
    ]
