# Generated by Django 4.2.2 on 2023-07-11 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_bimacoreaddress_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalpermission',
            options={'default_permissions': ()},
        ),
    ]
