# Generated by Django 4.2.2 on 2023-07-20 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_bimacoredocument_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimacoredepartment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.bimacoredepartment'),
        ),
    ]
