# Generated by Django 4.2.3 on 2023-08-17 09:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("treasury", "0003_bimatreasurypaymentterm_and_more"),
        ("core", "0028_alter_bimacoredepartment_department"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BimaCoreCash",
        ),
    ]
