# Generated by Django 4.2.3 on 2023-09-19 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_bimacorenotificationtype_bimacorenotification_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bimacorenotificationtemplate",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="bimacorenotificationtemplate",
            name="notification_type",
            field=models.ForeignKey(
                error_messages={
                    "unique": "A template with this notification type already exists."
                },
                on_delete=django.db.models.deletion.CASCADE,
                to="core.bimacorenotificationtype",
                unique=True,
            ),
        ),
    ]
