# Generated by Django 4.2.3 on 2023-09-19 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_alter_bimacorenotificationtemplate_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bimacorenotificationtemplate",
            name="notification_type",
            field=models.OneToOneField(
                error_messages={
                    "unique": "A template with this notification type already exists."
                },
                on_delete=django.db.models.deletion.CASCADE,
                to="core.bimacorenotificationtype",
            ),
        ),
    ]
