# Generated by Django 4.2.3 on 2023-09-19 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_alter_bimacorenotificationtemplate_notification_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bimacorenotification",
            options={
                "default_permissions": (),
                "ordering": ["-date_sent"],
                "permissions": [],
            },
        ),
    ]
