# Generated by Django 4.2.3 on 2023-09-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_alter_bimacorenotification_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bimacorepost",
            name="department",
        ),
        migrations.AlterField(
            model_name="bimacoredocument",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("PARTNER_PICTURE", "PARTNER_PICTURE"),
                    ("PARTNER_PRIVATE_DOCUMENT", "PARTNER_PRIVATE_DOCUMENT"),
                    ("PARTNER_CIRET_DOCUMENT", "PARTNER_CIRET_DOCUMENT"),
                    ("COMPANY_LOGO", "Logo"),
                    ("COMPANY_DOCUMENT", "Documents"),
                    ("EMPLOYEE_CV", "EMPLOYEE_CV"),
                    ("EMPLOYEE_RESUME", "EMPLOYEE_RESUME"),
                    ("EMPLOYEE_DRIVER_LICENCE", "EMPLOYEE_DRIVER_LICENCE"),
                    ("EMPLOYEE_PICTURE", "EMPLOYEE_PICTURE"),
                    ("EMPLOYEE_CONTRACT", "EMPLOYEE_CONTRACT"),
                    ("USER_PROFILE_PICTURE", "USER_PROFILE_PICTURE"),
                    ("USER_OTHER", "USER_OTHER"),
                    (
                        "SELLER_PURCHASE_QUOTE_DOCUMENT",
                        "SELLER_PURCHASE_QUOTE_DOCUMENT",
                    ),
                    (
                        "SELLER_PURCHASE_ORDER_DOCUMENT",
                        "SELLER_PURCHASE_ORDER_DOCUMENT",
                    ),
                    (
                        "SELLER_PURCHASE_INVOICE_DOCUMENT",
                        "SELLER_PURCHASE_INVOICE_DOCUMENT",
                    ),
                ],
                max_length=128,
            ),
        ),
    ]
