# Generated by Django 4.2.3 on 2023-09-25 13:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0002_bimahrjobcategory_bimahrperson_and_more"),
        ("core", "0034_remove_bimacorepost_department_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BimaCorePost",
        ),
    ]
