# Generated by Django 4.2.3 on 2023-09-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_delete_bimacorepost"),
    ]

    operations = [
        migrations.AddField(
            model_name="bimacoresource",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
