# Generated by Django 4.2.3 on 2023-07-27 08:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BimaTreasuryPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('bank_or_cash', models.PositiveIntegerField(choices=[(1, 'Bank'), (2, 'Cash')])),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'permissions': [],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BimaTreasuryPaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('credentials', models.JSONField(blank=True, null=True)),
                ('supports_tokenization', models.BooleanField(default=False, null=True)),
                ('supports_manual_capture', models.BooleanField(default=False, null=True)),
                ('supports_refunds', models.BooleanField(default=False, null=True)),
            ],
            options={
                'ordering': ['name'],
                'permissions': [],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BimaTreasuryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], default='income', max_length=10)),
                ('amount', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField()),
            ],
            options={
                'ordering': ['-date'],
                'permissions': [],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BimaTreasuryTransactionPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('reference', models.CharField(blank=True, max_length=128, null=True)),
                ('idempotency_token', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('is_captured', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treasury.bimatreasurypaymentmethod')),
                ('payment_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treasury.bimatreasurypaymentprovider')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treasury.bimatreasurytransaction')),
            ],
            options={
                'ordering': ['-created'],
                'permissions': [],
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='bimatreasurytransaction',
            name='transaction_payment_method',
            field=models.ManyToManyField(through='treasury.BimaTreasuryTransactionPaymentMethod', to='treasury.bimatreasurypaymentmethod'),
        ),
    ]
