# Generated by Django 4.2.3 on 2023-07-27 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0036_bimaerpunitofmeasure_is_default_for_service_product'),
        ('core', '0028_alter_bimacoredepartment_department'),
        ('treasury', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimatreasurytransaction',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='erp.bimaerppartner'),
        ),
        migrations.AddField(
            model_name='bimatreasurytransactionpaymentmethod',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bimacorebank'),
        ),
        migrations.AddField(
            model_name='bimatreasurytransactionpaymentmethod',
            name='cash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bimacorecash'),
        ),
    ]
