<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-05-21 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("erp", "0003_initial"),
        ("treasury", "0001_initial"),
=======
# Generated by Django 4.2.3 on 2024-05-21 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("erp", "0002_initial"),
        ("company", "0002_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("treasury", "0001_initial"),
        ("core", "0002_initial"),
>>>>>>> origin/ma-branch
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalbimatreasurytransaction",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalbimatreasurytransaction",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="erp.bimaerppartner",
                verbose_name="Partner",
            ),
        ),
        migrations.AddField(
            model_name="historicalbimatreasurytransaction",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="treasury.bimatreasurypaymentmethod",
                verbose_name="Transaction Type",
            ),
        ),
        migrations.AddField(
            model_name="historicalbimatreasurytransaction",
            name="transaction_source",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="treasury.bimatreasurytransaction",
                verbose_name="Transaction Source",
            ),
        ),
        migrations.AddField(
            model_name="historicalbimatreasurytransaction",
            name="transaction_type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="treasury.bimatreasurytransactiontype",
                verbose_name="Transaction Type",
            ),
        ),
        migrations.AddField(
<<<<<<< HEAD
            model_name="transactionpurchasedocumentpayment",
            name="purchase_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="erp.bimaerppurchasedocument",
            ),
        ),
        migrations.AddField(
            model_name="transactionpurchasedocumentpayment",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="treasury.bimatreasurytransaction",
            ),
        ),
        migrations.AddField(
            model_name="transactionsaledocumentpayment",
            name="sale_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="erp.bimaerpsaledocument",
            ),
        ),
        migrations.AddField(
            model_name="transactionsaledocumentpayment",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="treasury.bimatreasurytransaction",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="transactionpurchasedocumentpayment",
            unique_together={("transaction", "purchase_document")},
=======
            model_name="bimatreasurytransaction",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="treasury.bimatreasurybankaccount",
                verbose_name="Bank Account",
            ),
        ),
        migrations.AddField(
            model_name="bimatreasurytransaction",
            name="cash",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="treasury.bimatreasurycash",
                verbose_name="Cash",
            ),
        ),
        migrations.AddField(
            model_name="bimatreasurytransaction",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="erp.bimaerppartner",
                verbose_name="Partner",
            ),
        ),
        migrations.AddField(
            model_name="bimatreasurytransaction",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="treasury.bimatreasurypaymentmethod",
                verbose_name="Transaction Type",
            ),
        ),
        migrations.AddField(
            model_name="bimatreasurytransaction",
            name="transaction_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="treasury.bimatreasurytransaction",
                verbose_name="Transaction Source",
            ),
        ),
        migrations.AddField(
            model_name="bimatreasurytransaction",
            name="transaction_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="treasury.bimatreasurytransactiontype",
                verbose_name="Transaction Type",
            ),
        ),
        migrations.AddField(
            model_name="bimatreasurypaymenttermdetail",
            name="payment_term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_term_details",
                to="treasury.bimatreasurypaymentterm",
            ),
        ),
        migrations.AddField(
            model_name="bimatreasurycash",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="company.bimacompany"
            ),
        ),
        migrations.AddField(
            model_name="bimatreasurybankaccount",
            name="bank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="core.bimacorebank",
                verbose_name="Bank",
            ),
        ),
        migrations.AddField(
            model_name="bimatreasurybankaccount",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="core.bimacorecurrency",
                verbose_name="Currency",
            ),
        ),
        migrations.AddField(
            model_name="bimatreasurybankaccount",
            name="parent_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
>>>>>>> origin/ma-branch
        ),
        migrations.AlterUniqueTogether(
            name="transactionsaledocumentpayment",
            unique_together={("transaction", "sale_document")},
        ),
<<<<<<< HEAD
=======
        migrations.AlterUniqueTogether(
            name="transactionpurchasedocumentpayment",
            unique_together={("transaction", "purchase_document")},
        ),
>>>>>>> origin/ma-branch
    ]
