# Generated by Django 4.2.3 on 2023-08-17 09:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0010_alter_bimacompany_default_font_family"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0028_alter_bimacoredepartment_department"),
        ("treasury", "0002_bimatreasurytransaction_partner_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BimaTreasuryPaymentTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("active", models.BooleanField(default=True)),
                (
                    "note",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description/Note"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "permissions": [],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="BimaTreasuryPaymentTermDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("value", models.DecimalField(decimal_places=3, max_digits=5)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PERCENT", "Percentage"),
                            ("FIXED", "Fixed Amount"),
                            ("BALANCE", "Balance"),
                        ],
                        max_length=50,
                        verbose_name="Type",
                    ),
                ),
                (
                    "number_of_days",
                    models.PositiveIntegerField(verbose_name="Number of Days"),
                ),
                (
                    "day_of_month",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Day of the Month"
                    ),
                ),
                (
                    "payment_term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_term_details",
                        to="treasury.bimatreasurypaymentterm",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Payment Term Lines",
                "ordering": ["name"],
                "permissions": [],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="BimaTreasuryCash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="company.bimacompany",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "permissions": [],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="BimaTreasuryBankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("account_number", models.CharField(max_length=50, verbose_name="RIB")),
                (
                    "iban",
                    models.CharField(
                        blank=True, max_length=34, null=True, verbose_name="IBAN"
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=3, max_digits=14, verbose_name="Balance"
                    ),
                ),
                (
                    "account_holder_name",
                    models.CharField(
                        max_length=255, verbose_name="Account Holder Name"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.bimacorebank",
                        verbose_name="Bank",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.bimacorecurrency",
                        verbose_name="Currency",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "permissions": [],
                "default_permissions": (),
            },
        ),
        migrations.AlterField(
            model_name="bimatreasurytransactionpaymentmethod",
            name="cash",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="treasury.bimatreasurycash",
            ),
        ),
    ]
