# Generated by Django 4.2.3 on 2023-08-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treasury", "0004_bimatreasurypaymentterm_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bimatreasurypaymentterm",
            name="code",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
