# Generated by Django 4.2.3 on 2023-08-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treasury", "0005_alter_bimatreasurypaymentterm_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bimatreasurybankaccount",
            name="balance",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=14, verbose_name="Balance"
            ),
        ),
    ]
