# Generated by Django 4.2.3 on 2023-08-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treasury", "0006_alter_bimatreasurybankaccount_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bimatreasurybankaccount",
            name="account_number",
            field=models.CharField(max_length=50, unique=True, verbose_name="RIB"),
        ),
        migrations.AlterField(
            model_name="bimatreasurybankaccount",
            name="iban",
            field=models.CharField(
                blank=True, max_length=34, null=True, unique=True, verbose_name="IBAN"
            ),
        ),
    ]
