# Generated by Django 4.2.3 on 2023-08-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treasury", "0007_alter_bimatreasurybankaccount_account_number_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bimatreasurybankaccount",
            old_name="notes",
            new_name="note",
        ),
        migrations.RenameField(
            model_name="bimatreasurycash",
            old_name="notes",
            new_name="note",
        ),
        migrations.AddField(
            model_name="bimatreasurybankaccount",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
