# Generated by Django 4.2.3 on 2023-08-17 11:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("treasury", "0008_rename_notes_bimatreasurybankaccount_note_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BimaTreasuryTransactionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("active", models.BooleanField(default=True)),
                (
                    "note",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description/Note"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=128, null=True, unique=True
                    ),
                ),
                ("is_system", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["name"],
                "permissions": [],
                "default_permissions": (),
            },
        ),
    ]
