# Generated by Django 4.2.3 on 2023-08-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treasury", "0009_bimatreasurytransactiontype"),
    ]

    operations = [
        migrations.AddField(
            model_name="bimatreasurytransactiontype",
            name="income_outcome",
            field=models.CharField(
                blank=True,
                choices=[("INCOME", "INCOME"), ("OUTCOME", "OUTCOME")],
                max_length=32,
                null=True,
                verbose_name="INCOME_OUTCOME",
            ),
        ),
    ]
