# Generated by Django 4.2.3 on 2023-08-18 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("erp", "0049_remove_bimaerppurchasedocument_payment_term_and_more"),
        ("treasury", "0011_alter_bimatreasurytransactiontype_income_outcome"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalBimaTreasuryTransaction",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("updated", models.DateTimeField(blank=True, editable=False)),
                (
                    "nature",
                    models.CharField(
                        choices=[("CASH", "Cash"), ("BANK", "Bank")],
                        max_length=5,
                        verbose_name="Nature",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("INCOME", "Income"), ("OUTCOME", "Outcome")],
                        max_length=7,
                        verbose_name="Direction",
                    ),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="Notes")),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "expected_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Expected Date"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=3, max_digits=14, verbose_name="Amount"
                    ),
                ),
                (
                    "partner_bank_account_number",
                    models.CharField(max_length=32, verbose_name="Bank account number"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical bima treasury transaction",
                "verbose_name_plural": "historical bima treasury transactions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name="bimatreasurytransactionpaymentmethod",
            name="bank",
        ),
        migrations.RemoveField(
            model_name="bimatreasurytransactionpaymentmethod",
            name="cash",
        ),
        migrations.RemoveField(
            model_name="bimatreasurytransactionpaymentmethod",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="bimatreasurytransactionpaymentmethod",
            name="payment_provider",
        ),
        migrations.RemoveField(
            model_name="bimatreasurytransactionpaymentmethod",
            name="transaction",
        ),
        migrations.AlterModelOptions(
            name="bimatreasurytransaction",
            options={},
        ),
        migrations.RenameField(
            model_name="bimatreasurybankaccount",
            old_name="object_id",
            new_name="parent_id",
        ),
        migrations.RenameField(
            model_name="bimatreasurybankaccount",
            old_name="content_type",
            new_name="parent_type",
        ),
        migrations.RemoveField(
            model_name="bimatreasurytransaction",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="bimatreasurytransaction",
            name="name",
        ),
        migrations.RemoveField(
            model_name="bimatreasurytransaction",
            name="transaction_payment_method",
        ),
        migrations.AddField(
            model_name="bimatreasurycash",
            name="balance",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=14, verbose_name="Balance"
            ),
        ),
        migrations.AddField(
            model_name="bimatreasurytransaction",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="treasury.bimatreasurybankaccount",
                verbose_name="Bank Account",
            ),
        ),
        migrations.AddField(
            model_name="bimatreasurytransaction",
            name="cash",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="treasury.bimatreasurycash",
                verbose_name="Cash",
            ),
        ),
        migrations.AddField(
            model_name="bimatreasurytransaction",
            name="direction",
            field=models.CharField(
                choices=[("INCOME", "Income"), ("OUTCOME", "Outcome")],
                default="income",
                max_length=7,
                verbose_name="Direction",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bimatreasurytransaction",
            name="expected_date",
            field=models.DateField(blank=True, null=True, verbose_name="Expected Date"),
        ),
        migrations.AddField(
            model_name="bimatreasurytransaction",
            name="nature",
            field=models.CharField(
                choices=[("CASH", "Cash"), ("BANK", "Bank")],
                default="cash",
                max_length=5,
                verbose_name="Nature",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bimatreasurytransaction",
            name="partner_bank_account_number",
            field=models.CharField(
                default="", max_length=32, verbose_name="Bank account number"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bimatreasurytransaction",
            name="transaction_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="treasury.bimatreasurytransaction",
                verbose_name="Transaction Source",
            ),
        ),
        migrations.AddField(
            model_name="bimatreasurytransactiontype",
            name="cash_bank",
            field=models.CharField(
                choices=[("Cash", "Cash"), ("Bank", "Bank")],
                default=None,
                max_length=32,
                verbose_name="INCOME_OUTCOME",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bimatreasurytransaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=3, max_digits=14, verbose_name="Amount"
            ),
        ),
        migrations.AlterField(
            model_name="bimatreasurytransaction",
            name="date",
            field=models.DateField(verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="bimatreasurytransaction",
            name="note",
            field=models.TextField(blank=True, null=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="bimatreasurytransaction",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="erp.bimaerppartner",
                verbose_name="Partner",
            ),
        ),
        migrations.AlterField(
            model_name="bimatreasurytransaction",
            name="transaction_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="treasury.bimatreasurytransactiontype",
                verbose_name="Transaction Type",
            ),
        ),
        migrations.DeleteModel(
            name="BimaTreasuryPaymentMethod",
        ),
        migrations.DeleteModel(
            name="BimaTreasuryPaymentProvider",
        ),
        migrations.DeleteModel(
            name="BimaTreasuryTransactionPaymentMethod",
        ),
        migrations.AddField(
            model_name="historicalbimatreasurytransaction",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="treasury.bimatreasurybankaccount",
                verbose_name="Bank Account",
            ),
        ),
        migrations.AddField(
            model_name="historicalbimatreasurytransaction",
            name="cash",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="treasury.bimatreasurycash",
                verbose_name="Cash",
            ),
        ),
        migrations.AddField(
            model_name="historicalbimatreasurytransaction",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalbimatreasurytransaction",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="erp.bimaerppartner",
                verbose_name="Partner",
            ),
        ),
        migrations.AddField(
            model_name="historicalbimatreasurytransaction",
            name="transaction_source",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="treasury.bimatreasurytransaction",
                verbose_name="Transaction Source",
            ),
        ),
        migrations.AddField(
            model_name="historicalbimatreasurytransaction",
            name="transaction_type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="treasury.bimatreasurytransactiontype",
                verbose_name="Transaction Type",
            ),
        ),
    ]
