# Generated by Django 4.2.3 on 2023-08-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treasury", "0012_historicalbimatreasurytransaction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bimatreasurytransaction",
            name="partner_bank_account_number",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Bank account number"
            ),
        ),
        migrations.AlterField(
            model_name="historicalbimatreasurytransaction",
            name="partner_bank_account_number",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Bank account number"
            ),
        ),
    ]
