# Generated by Django 4.2.3 on 2023-08-21 08:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "treasury",
            "0013_alter_bimatreasurytransaction_partner_bank_account_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bimatreasurypaymenttermdetail",
            options={},
        ),
        migrations.RemoveField(
            model_name="bimatreasurypaymenttermdetail",
            name="created",
        ),
        migrations.RemoveField(
            model_name="bimatreasurypaymenttermdetail",
            name="day_of_month",
        ),
        migrations.RemoveField(
            model_name="bimatreasurypaymenttermdetail",
            name="name",
        ),
        migrations.RemoveField(
            model_name="bimatreasurypaymenttermdetail",
            name="number_of_days",
        ),
        migrations.RemoveField(
            model_name="bimatreasurypaymenttermdetail",
            name="public_id",
        ),
        migrations.RemoveField(
            model_name="bimatreasurypaymenttermdetail",
            name="type",
        ),
        migrations.RemoveField(
            model_name="bimatreasurypaymenttermdetail",
            name="updated",
        ),
        migrations.AddField(
            model_name="bimatreasurypaymentterm",
            name="type",
            field=models.CharField(
                choices=[
                    ("IMMEDIATE", "IMMEDIATE"),
                    ("AFTER_ONE_WEEK", "AFTER_ONE_WEEK"),
                    ("AFTER_TWO_WEEK", "AFTER_TWO_WEEK"),
                    ("END_OF_MONTH", "END_OF_MONTH"),
                    ("CUSTOM", "CUSTOM"),
                ],
                default=1,
                max_length=64,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bimatreasurypaymenttermdetail",
            name="percentage",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bimatreasurypaymenttermdetail",
            name="payment_term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_term_details",
                to="treasury.bimatreasurypaymentterm",
            ),
        ),
        migrations.AlterField(
            model_name="bimatreasurypaymenttermdetail",
            name="value",
            field=models.CharField(
                choices=[
                    ("IMMEDIATE", "IMMEDIATE"),
                    ("AFTER_ONE_WEEK", "AFTER_ONE_WEEK"),
                    ("AFTER_TWO_WEEK", "AFTER_TWO_WEEK"),
                    ("END_OF_MONTH", "END_OF_MONTH"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="bimatreasurytransactiontype",
            name="cash_bank",
            field=models.CharField(
                choices=[("Cash", "Cash"), ("Bank", "Bank")],
                max_length=32,
                verbose_name="CASH_BANK",
            ),
        ),
    ]
