# Generated by Django 4.2.3 on 2023-08-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treasury", "0016_alter_bimatreasurypaymenttermdetail_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bimatreasurypaymentterm",
            name="type",
            field=models.CharField(
                choices=[
                    ("IMMEDIATE", "IMMEDIATE"),
                    ("AFTER_ONE_WEEK", "AFTER_ONE_WEEK"),
                    ("AFTER_TWO_WEEK", "AFTER_TWO_WEEK"),
                    ("END_OF_MONTH", "END_OF_MONTH"),
                    ("NEXT_MONTH", "NEXT_MONTH"),
                    ("CUSTOM", "CUSTOM"),
                ],
                max_length=64,
            ),
        ),
    ]
