# Generated by Django 4.2.3 on 2023-08-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treasury", "0017_alter_bimatreasurypaymentterm_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="bimatreasurytransaction",
            name="reference",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Reference"
            ),
        ),
        migrations.AddField(
            model_name="historicalbimatreasurytransaction",
            name="reference",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Reference"
            ),
        ),
    ]
