# Generated by Django 4.2.3 on 2023-08-29 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0053_bimaerpsaledocument_payment_terms_and_more"),
        ("treasury", "0018_bimatreasurytransaction_reference_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionSaleDocumentPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_paid", models.DecimalField(decimal_places=3, max_digits=14)),
                (
                    "sale_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp.bimaerpsaledocument",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="treasury.bimatreasurytransaction",
                    ),
                ),
            ],
            options={
                "unique_together": {("transaction", "sale_document")},
            },
        ),
    ]
