# Generated by Django 4.2.3 on 2023-08-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treasury", "0020_bimatreasurytransaction_remaining_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bimatreasurytransaction",
            name="number",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Number"
            ),
        ),
        migrations.AddField(
            model_name="historicalbimatreasurytransaction",
            name="number",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Number"
            ),
        ),
    ]
