# Generated by Django 4.2.3 on 2023-08-31 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0056_bimaerppurchasedocument_amount_paid_and_more"),
        ("treasury", "0021_bimatreasurytransaction_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionPurchaseDocumentPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_paid", models.DecimalField(decimal_places=3, max_digits=14)),
                (
                    "purchase_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp.bimaerppurchasedocument",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="treasury.bimatreasurytransaction",
                    ),
                ),
            ],
            options={
                "unique_together": {("transaction", "purchase_document")},
            },
        ),
    ]
