# Generated by Django 4.2.3 on 2023-08-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treasury", "0022_transactionpurchasedocumentpayment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bimatreasurytransaction",
            name="number",
            field=models.CharField(max_length=32, unique=True, verbose_name="Number"),
        ),
        migrations.AlterField(
            model_name="historicalbimatreasurytransaction",
            name="number",
            field=models.CharField(db_index=True, max_length=32, verbose_name="Number"),
        ),
    ]
