# Generated by Django 4.2.3 on 2023-09-01 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("treasury", "0024_bimatreasurypaymentmethod"),
    ]

    operations = [
        migrations.AddField(
            model_name="bimatreasurytransaction",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="treasury.bimatreasurypaymentmethod",
                verbose_name="Transaction Type",
            ),
        ),
        migrations.AddField(
            model_name="historicalbimatreasurytransaction",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="treasury.bimatreasurypaymentmethod",
                verbose_name="Transaction Type",
            ),
        ),
    ]
