# Generated by Django 4.2.3 on 2023-09-19 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("treasury", "0025_bimatreasurytransaction_payment_method_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bimatreasurytransaction",
            options={
                "default_permissions": (),
                "ordering": ["-date"],
                "permissions": [],
            },
        ),
    ]
