# Generated by Django 4.2.1 on 2023-05-18 08:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BimaPartners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('supplier', models.BooleanField(blank=True, null=True)),
                ('customer', models.BooleanField(blank=True, null=True)),
                ('name_supplier', models.BooleanField(blank=True, null=True)),
                ('name_customer', models.BooleanField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Phone', models.CharField(blank=True, null=True)),
                ('Fax', models.CharField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
