# Generated by Django 4.2.1 on 2023-05-30 08:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BimaErpPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_supplier', models.BooleanField(blank=True, null=True)),
                ('is_customer', models.BooleanField(blank=True, null=True)),
                ('partner_type', models.CharField(max_length=128)),
                ('company_type', models.CharField(max_length=256)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=32)),
                ('social_security_number', models.CharField(max_length=64)),
                ('id_number', models.CharField(max_length=64)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Phone', models.CharField(blank=True, null=True)),
                ('Fax', models.CharField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, null=True)),
                ('company_activity', models.CharField(blank=True, null=True)),
                ('vat_id_number', models.CharField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'ACTIVE'), ('Inactive', 'INACTIVE'), ('Blocked', 'BLOCKED')], max_length=32, null=True)),
                ('note', models.CharField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='BimaPartners',
        ),
    ]
