<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-05-21 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("erp", "0001_initial"),
        ("treasury", "0001_initial"),
=======
# Generated by Django 4.2.3 on 2024-05-21 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("treasury", "0001_initial"),
        ("erp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> origin/ma-branch
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name="bimaerppurchasedocument",
            name="payment_terms",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
=======
            model_name="historicalbimaerpsaledocumentproduct",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalbimaerpsaledocumentproduct",
            name="product",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="erp.bimaerpproduct",
            ),
        ),
        migrations.AddField(
            model_name="historicalbimaerpsaledocumentproduct",
            name="sale_document",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="erp.bimaerpsaledocument",
            ),
        ),
        migrations.AddField(
            model_name="historicalbimaerpsaledocument",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalbimaerpsaledocument",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="erp.bimaerppartner",
                verbose_name="Partner",
            ),
        ),
        migrations.AddField(
            model_name="historicalbimaerpsaledocument",
            name="payment_terms",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
>>>>>>> origin/ma-branch
                to="treasury.bimatreasurypaymentterm",
                verbose_name="Payment Terms",
            ),
        ),
        migrations.AddField(
<<<<<<< HEAD
            model_name="bimaerppurchasedocument",
            name="transactions",
            field=models.ManyToManyField(
                related_name="purchase_documents",
                through="treasury.TransactionPurchaseDocumentPayment",
                to="treasury.bimatreasurytransaction",
            ),
        ),
        migrations.AddField(
            model_name="bimaerppurchasedocumentproduct",
=======
            model_name="historicalbimaerpsaledocument",
            name="recurring_reactivated_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Recurring Reactivated By",
            ),
        ),
        migrations.AddField(
            model_name="historicalbimaerpsaledocument",
            name="recurring_stopped_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Recurring Stopped By",
            ),
        ),
        migrations.AddField(
            model_name="historicalbimaerppurchasedocumentproduct",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalbimaerppurchasedocumentproduct",
            name="product",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="erp.bimaerpproduct",
            ),
        ),
        migrations.AddField(
            model_name="historicalbimaerppurchasedocumentproduct",
            name="purchase_document",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="erp.bimaerppurchasedocument",
            ),
        ),
        migrations.AddField(
            model_name="historicalbimaerppurchasedocument",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalbimaerppurchasedocument",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="erp.bimaerppartner",
            ),
        ),
        migrations.AddField(
            model_name="historicalbimaerppurchasedocument",
            name="payment_terms",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="treasury.bimatreasurypaymentterm",
                verbose_name="Payment Terms",
            ),
        ),
        migrations.AddField(
            model_name="bimaerpsaledocumentproduct",
>>>>>>> origin/ma-branch
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="erp.bimaerpproduct"
            ),
        ),
        migrations.AddField(
<<<<<<< HEAD
            model_name="bimaerppurchasedocumentproduct",
            name="purchase_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="erp.bimaerppurchasedocument",
            ),
        ),
        migrations.AddField(
            model_name="bimaerppurchasedocument",
            name="purchase_document_products",
            field=models.ManyToManyField(
                through="erp.BimaErpPurchaseDocumentProduct", to="erp.bimaerpproduct"
=======
            model_name="bimaerpsaledocumentproduct",
            name="sale_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="erp.bimaerpsaledocument",
>>>>>>> origin/ma-branch
            ),
        ),
        migrations.AddField(
            model_name="bimaerpsaledocument",
            name="parents",
            field=models.ManyToManyField(
                blank=True, to="erp.bimaerpsaledocument", verbose_name="Parents"
            ),
        ),
        migrations.AddField(
            model_name="bimaerpsaledocument",
            name="partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="erp.bimaerppartner",
                verbose_name="Partner",
            ),
        ),
        migrations.AddField(
            model_name="bimaerpsaledocument",
            name="payment_terms",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="treasury.bimatreasurypaymentterm",
                verbose_name="Payment Terms",
            ),
        ),
<<<<<<< HEAD
=======
        migrations.AddField(
            model_name="bimaerpsaledocument",
            name="recurring_reactivated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reactivated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Recurring Reactivated By",
            ),
        ),
        migrations.AddField(
            model_name="bimaerpsaledocument",
            name="recurring_stopped_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stopped_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Recurring Stopped By",
            ),
        ),
        migrations.AddField(
            model_name="bimaerpsaledocument",
            name="sale_document_products",
            field=models.ManyToManyField(
                through="erp.BimaErpSaleDocumentProduct",
                to="erp.bimaerpproduct",
                verbose_name="Sale Document Products",
            ),
        ),
        migrations.AddField(
            model_name="bimaerpsaledocument",
            name="transactions",
            field=models.ManyToManyField(
                related_name="sale_documents",
                through="treasury.TransactionSaleDocumentPayment",
                to="treasury.bimatreasurytransaction",
            ),
        ),
        migrations.AddField(
            model_name="bimaerppurchasedocumentproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="erp.bimaerpproduct"
            ),
        ),
        migrations.AddField(
            model_name="bimaerppurchasedocumentproduct",
            name="purchase_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="erp.bimaerppurchasedocument",
            ),
        ),
        migrations.AddField(
            model_name="bimaerppurchasedocument",
            name="parents",
            field=models.ManyToManyField(blank=True, to="erp.bimaerppurchasedocument"),
        ),
        migrations.AddField(
            model_name="bimaerppurchasedocument",
            name="partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="erp.bimaerppartner"
            ),
        ),
        migrations.AddField(
            model_name="bimaerppurchasedocument",
            name="payment_terms",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="treasury.bimatreasurypaymentterm",
                verbose_name="Payment Terms",
            ),
        ),
        migrations.AddField(
            model_name="bimaerppurchasedocument",
            name="purchase_document_products",
            field=models.ManyToManyField(
                through="erp.BimaErpPurchaseDocumentProduct", to="erp.bimaerpproduct"
            ),
        ),
        migrations.AddField(
            model_name="bimaerppurchasedocument",
            name="transactions",
            field=models.ManyToManyField(
                related_name="purchase_documents",
                through="treasury.TransactionPurchaseDocumentPayment",
                to="treasury.bimatreasurytransaction",
            ),
        ),
        migrations.AddField(
            model_name="bimaerpproduct",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="erp.bimaerpcategory",
                verbose_name="Category",
            ),
        ),
        migrations.AddField(
            model_name="bimaerpproduct",
            name="unit_of_measure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="erp.bimaerpunitofmeasure",
                verbose_name="Unit of Measure",
            ),
        ),
        migrations.AddField(
            model_name="bimaerpproduct",
            name="vat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="erp.bimaerpvat",
                verbose_name="VAT",
            ),
        ),
        migrations.AddField(
            model_name="bimaerpcategory",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="erp.bimaerpcategory",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bimaerpsaledocumentproduct",
            unique_together={("sale_document", "product")},
        ),
        migrations.AlterUniqueTogether(
            name="bimaerppurchasedocumentproduct",
            unique_together={("purchase_document", "product")},
        ),
>>>>>>> origin/ma-branch
    ]
