# Generated by Django 5.0.6 on 2024-05-21 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("erp", "0001_initial"),
        ("treasury", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bimaerppurchasedocument",
            name="payment_terms",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="treasury.bimatreasurypaymentterm",
                verbose_name="Payment Terms",
            ),
        ),
        migrations.AddField(
            model_name="bimaerppurchasedocument",
            name="transactions",
            field=models.ManyToManyField(
                related_name="purchase_documents",
                through="treasury.TransactionPurchaseDocumentPayment",
                to="treasury.bimatreasurytransaction",
            ),
        ),
        migrations.AddField(
            model_name="bimaerppurchasedocumentproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="erp.bimaerpproduct"
            ),
        ),
        migrations.AddField(
            model_name="bimaerppurchasedocumentproduct",
            name="purchase_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="erp.bimaerppurchasedocument",
            ),
        ),
        migrations.AddField(
            model_name="bimaerppurchasedocument",
            name="purchase_document_products",
            field=models.ManyToManyField(
                through="erp.BimaErpPurchaseDocumentProduct", to="erp.bimaerpproduct"
            ),
        ),
        migrations.AddField(
            model_name="bimaerpsaledocument",
            name="parents",
            field=models.ManyToManyField(
                blank=True, to="erp.bimaerpsaledocument", verbose_name="Parents"
            ),
        ),
        migrations.AddField(
            model_name="bimaerpsaledocument",
            name="partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="erp.bimaerppartner",
                verbose_name="Partner",
            ),
        ),
        migrations.AddField(
            model_name="bimaerpsaledocument",
            name="payment_terms",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="treasury.bimatreasurypaymentterm",
                verbose_name="Payment Terms",
            ),
        ),
    ]
