# Generated by Django 4.2.1 on 2023-05-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_bimaerppartner_delete_bimapartners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimaerppartner',
            name='company_type',
            field=models.CharField(blank=True, choices=[('Sole proprietorship', 'SOLE_PROPRIETORSHIP'), ('General partnership', 'GENERAL_PARTNERSHIP'), ('Limited partnership', 'LIMITED_PARTNERSHIP'), ('Public limited company(PLC)', 'PUBLIC_LIMITED_COMPANY_PLC'), ('Limited liability company(LLC)', 'LIMITED_LIABILITY_COMPANY_LLC'), ('Simplified joint - stock', 'SIMPLIFIED_JOINT_STOCK'), ('company Partnership limited by shares', 'COMPANY_PARTNERSHIP_LIMITED_BY_SHARES'), ('Cooperative society', 'COOPERATIVE_SOCIETY'), ('Unincorporated joint venture', 'UNINCORPORATED_JOINT_VENTURE'), ('Joint - stock company', 'JOINT_STOCK_COMPANY')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='bimaerppartner',
            name='partner_type',
            field=models.CharField(choices=[('Individual', 'INDIVIDUAL'), ('Company', 'COMPANY')], max_length=128),
        ),
    ]
