# Generated by Django 4.2.1 on 2023-05-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_alter_bimaerppartner_company_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimaerppartner',
            name='company_type',
            field=models.CharField(blank=True, choices=[('SOLE_PROPRIETORSHIP', 'Sole proprietorship'), ('GENERAL_PARTNERSHIP', 'General partnership'), ('LIMITED_PARTNERSHIP', 'Limited partnership'), ('PUBLIC_LIMITED_COMPANY_PLC', 'Public limited company(PLC)'), ('LIMITED_LIABILITY_COMPANY_LLC', 'Limited liability company(LLC)'), ('SIMPLIFIED_JOINT_STOCK', 'Simplified joint - stock'), ('COMPANY_PARTNERSHIP_LIMITED_BY_SHARES', 'company Partnership limited by shares'), ('COOPERATIVE_SOCIETY', 'Cooperative society'), ('UNINCORPORATED_JOINT_VENTURE', 'Unincorporated joint venture'), ('JOINT_STOCK_COMPANY', 'Joint - stock company')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='bimaerppartner',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=32),
        ),
        migrations.AlterField(
            model_name='bimaerppartner',
            name='partner_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company')], max_length=128),
        ),
        migrations.AlterField(
            model_name='bimaerppartner',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked')], max_length=32, null=True),
        ),
    ]
