# Generated by Django 4.2.1 on 2023-06-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_rename_email_bimaerppartner_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimaerppartner',
            name='company_ape_code',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bimaerppartner',
            name='company_ape_text',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bimaerppartner',
            name='company_budget',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bimaerppartner',
            name='company_date_creation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bimaerppartner',
            name='company_date_registration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bimaerppartner',
            name='company_date_struck_off',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bimaerppartner',
            name='company_siren',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bimaerppartner',
            name='company_siret',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bimaerppartner',
            name='graft',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bimaerppartner',
            name='number_siret',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bimaerppartner',
            name='rcs',
            field=models.CharField(blank=True, null=True),
        ),
    ]
