# Generated by Django 4.2.1 on 2023-06-05 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_bimaerppartner_company_ape_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bimaerppartner',
            old_name='company_budget',
            new_name='company_capital',
        ),
        migrations.RenameField(
            model_name='bimaerppartner',
            old_name='graft',
            new_name='rcs_number',
        ),
        migrations.RemoveField(
            model_name='bimaerppartner',
            name='number_siret',
        ),
        migrations.RemoveField(
            model_name='bimaerppartner',
            name='rcs',
        ),
    ]
