# Generated by Django 4.2.1 on 2023-06-06 09:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_rename_company_budget_bimaerppartner_company_capital_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BimaErpCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_children', to='erp.bimaerpcategory')),
            ],
            options={
                'ordering': ['name'],
                'permissions': [],
            },
        ),
        migrations.CreateModel(
            name='BimaErpUnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('active', models.BooleanField(default=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'permissions': [],
            },
        ),
        migrations.CreateModel(
            name='BimaErpVat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('rate', models.FloatField()),
                ('active', models.BooleanField(default=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'permissions': [],
            },
        ),
        migrations.CreateModel(
            name='BimaErpProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('ean13', models.CharField(blank=True, max_length=64, null=True)),
                ('type', models.CharField(choices=[('STOCKABLE_PRODUCT', 'Stockable Products'), ('SERVICE_PRODUCTS', 'Service Products'), ('PRODUCTION_PRODUCTS', 'Production Products')], max_length=255)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('price_calculation_method', models.CharField(choices=[('MANUAL', 'Manual Price'), ('PERCENTAGE', 'Price based on Percentage')], max_length=50)),
                ('sell_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('OUT_OF_STOCK', 'Out of Stock:'), ('IN_TRANSIT', 'In transit'), ('DISCONTINUED', 'Discontinued'), ('NOT_FOR_SALE', 'Not for sale')], max_length=50)),
                ('minimum_stock_level', models.PositiveIntegerField()),
                ('maximum_stock_level', models.PositiveIntegerField()),
                ('dimension', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.CharField(blank=True, max_length=255, null=True)),
                ('reorder_point', models.PositiveIntegerField()),
                ('lead_time', models.PositiveIntegerField()),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.bimaerpcategory')),
                ('vat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.bimaerpvat')),
            ],
            options={
                'ordering': ['name'],
                'permissions': [],
            },
        ),
    ]
