# Generated by Django 4.2.1 on 2023-06-06 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_bimaerpcategory_bimaerpunitofmeasure_bimaerpvat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimaerpproduct',
            name='unit_of_measure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='erp.bimaerpunitofmeasure'),
            preserve_default=False,
        ),
    ]
