# Generated by Django 4.2.1 on 2023-06-12 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0010_bimaerpproduct_unit_of_measure'),
    ]

    operations = [
        migrations.CreateModel(
            name='BimaErpSaleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('numbers', models.CharField(max_length=32)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('CANCELED', 'CANCELED')], default='DRAFT', max_length=128)),
                ('type', models.CharField(choices=[('QUOTE', 'Quote'), ('ORDER', 'ORDER'), ('INVOICE', 'Invoice')], default='DRAFT', max_length=128)),
                ('note', models.TextField(blank=True, null=True)),
                ('private_note', models.TextField(blank=True, null=True)),
                ('validity', models.CharField(blank=True, choices=[('day_30', '30 days'), ('day_15', '15 days'), ('day_10', '10 days'), ('day_45', '45 days')], null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_terms', models.CharField(blank=True, max_length=100, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('taxes', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('discounts', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('parents', models.ManyToManyField(blank=True, to='erp.bimaerpsaledocument')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.bimaerppartner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bimaerpproduct',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bimaerpproduct',
            name='virtual_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalBimaErpSaleDocument',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('numbers', models.CharField(max_length=32)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('CANCELED', 'CANCELED')], default='DRAFT', max_length=128)),
                ('type', models.CharField(choices=[('QUOTE', 'Quote'), ('ORDER', 'ORDER'), ('INVOICE', 'Invoice')], default='DRAFT', max_length=128)),
                ('note', models.TextField(blank=True, null=True)),
                ('private_note', models.TextField(blank=True, null=True)),
                ('validity', models.CharField(blank=True, choices=[('day_30', '30 days'), ('day_15', '15 days'), ('day_10', '10 days'), ('day_45', '45 days')], null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_terms', models.CharField(blank=True, max_length=100, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('taxes', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('discounts', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='erp.bimaerppartner')),
            ],
            options={
                'verbose_name': 'historical bima erp sale document',
                'verbose_name_plural': 'historical bima erp sale documents',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BimaErpSaleDocumentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=18)),
                ('vat', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.bimaerpproduct')),
                ('sale_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.bimaerpsaledocument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bimaerpsaledocument',
            name='products',
            field=models.ManyToManyField(through='erp.BimaErpSaleDocumentProduct', to='erp.bimaerpproduct'),
        ),
    ]
