# Generated by Django 4.2.1 on 2023-06-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_remove_bimaerpsaledocument_numbers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimaerpsaledocumentproduct',
            name='name',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bimaerpsaledocumentproduct',
            name='reference',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
