# Generated by Django 4.2.1 on 2023-06-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_bimaerpsaledocumentproduct_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bimaerpsaledocument',
            old_name='total',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='historicalbimaerpsaledocument',
            name='total',
        ),
        migrations.AddField(
            model_name='bimaerpsaledocument',
            name='total_discount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='bimaerpsaledocument',
            name='total_vat',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='bimaerpsaledocumentproduct',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='bimaerpsaledocumentproduct',
            name='total_after_discount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='bimaerpsaledocumentproduct',
            name='total_without_vat',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='bimaerpsaledocumentproduct',
            name='vat_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='historicalbimaerpsaledocument',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='historicalbimaerpsaledocument',
            name='total_discount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='historicalbimaerpsaledocument',
            name='total_vat',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
    ]
