# Generated by Django 4.2.1 on 2023-06-13 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_rename_total_bimaerpsaledocument_total_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bimaerpsaledocument',
            old_name='products',
            new_name='sale_document_products',
        ),
    ]
