# Generated by Django 4.2.1 on 2023-06-13 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_rename_products_bimaerpsaledocument_sale_document_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bimaerpsaledocumentproduct',
            name='created',
        ),
        migrations.RemoveField(
            model_name='bimaerpsaledocumentproduct',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='bimaerpsaledocumentproduct',
            name='updated',
        ),
    ]
