# Generated by Django 4.2.1 on 2023-06-13 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_remove_bimaerpsaledocumentproduct_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bimaerpsaledocument',
            name='discounts',
        ),
        migrations.RemoveField(
            model_name='bimaerpsaledocument',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='bimaerpsaledocument',
            name='taxes',
        ),
        migrations.RemoveField(
            model_name='historicalbimaerpsaledocument',
            name='discounts',
        ),
        migrations.RemoveField(
            model_name='historicalbimaerpsaledocument',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='historicalbimaerpsaledocument',
            name='taxes',
        ),
        migrations.AlterUniqueTogether(
            name='bimaerpsaledocumentproduct',
            unique_together={('sale_document', 'product')},
        ),
    ]
