# Generated by Django 4.2.1 on 2023-06-13 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0017_remove_bimaerpsaledocument_discounts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimaerpsaledocumentproduct',
            name='sale_document_public_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalBimaErpSaleDocumentProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sale_document_public_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=18)),
                ('vat', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('total_without_vat', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('total_after_discount', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='erp.bimaerpproduct')),
                ('sale_document', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='erp.bimaerpsaledocument')),
            ],
            options={
                'verbose_name': 'historical bima erp sale document product',
                'verbose_name_plural': 'historical bima erp sale document products',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
