# Generated by Django 4.2.1 on 2023-06-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0018_bimaerpsaledocumentproduct_sale_document_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimaerpproduct',
            name='lead_time',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bimaerpproduct',
            name='maximum_stock_level',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bimaerpproduct',
            name='minimum_stock_level',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bimaerpproduct',
            name='reorder_point',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
