# Generated by Django 4.2.1 on 2023-06-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0019_alter_bimaerpproduct_lead_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimaerpsaledocument',
            name='vat_amount',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='bimaerpsaledocument',
            name='vat_label',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='historicalbimaerpsaledocument',
            name='vat_amount',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='historicalbimaerpsaledocument',
            name='vat_label',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='bimaerpsaledocument',
            name='type',
            field=models.CharField(choices=[('QUOTE', 'Quote'), ('ORDER', 'ORDER'), ('INVOICE', 'Invoice')], default='Quote', max_length=128),
        ),
        migrations.AlterField(
            model_name='historicalbimaerpsaledocument',
            name='type',
            field=models.CharField(choices=[('QUOTE', 'Quote'), ('ORDER', 'ORDER'), ('INVOICE', 'Invoice')], default='Quote', max_length=128),
        ),
    ]
