# Generated by Django 4.2.1 on 2023-06-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0023_alter_bimaerpsaledocumentproduct_unit_of_measure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimaerpsaledocumentproduct',
            name='unit_of_measure',
            field=models.CharField(blank=True, default='default', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbimaerpsaledocumentproduct',
            name='unit_of_measure',
            field=models.CharField(blank=True, default='default', max_length=255, null=True),
        ),
    ]
