# Generated by Django 4.2.2 on 2023-06-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0025_alter_bimaerpsaledocumentproduct_unit_of_measure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimaerpproduct',
            name='reference',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
