# Generated by Django 4.2.2 on 2023-06-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0026_alter_bimaerpproduct_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimaerpsaledocument',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='bimaerpsaledocument',
            name='total_discount',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='bimaerpsaledocument',
            name='total_vat',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbimaerpsaledocument',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbimaerpsaledocument',
            name='total_discount',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbimaerpsaledocument',
            name='total_vat',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=18, null=True),
        ),
    ]
