# Generated by Django 4.2.2 on 2023-06-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0027_alter_bimaerpsaledocument_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimaerpsaledocument',
            name='total_after_discount',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='bimaerpsaledocument',
            name='total_amount_without_vat',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='historicalbimaerpsaledocument',
            name='total_after_discount',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='historicalbimaerpsaledocument',
            name='total_amount_without_vat',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=18, null=True),
        ),
    ]
