# Generated by Django 4.2.2 on 2023-06-26 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_bimaerpsaledocument_total_after_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimaerpsaledocumentproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.bimaerpproduct'),
        ),
        migrations.AlterField(
            model_name='bimaerpsaledocumentproduct',
            name='sale_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.bimaerpsaledocument'),
        ),
    ]
