# Generated by Django 4.2.2 on 2023-07-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0029_alter_bimaerpsaledocumentproduct_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimaerppartner',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='bimaerppartner',
            name='credit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='bimaerpcategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bimaerpunitofmeasure',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bimaerpvat',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bimaerpvat',
            name='rate',
            field=models.FloatField(unique=True),
        ),
    ]
