# Generated by Django 4.2.2 on 2023-07-04 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0031_bimaerppurchasedocument_alter_bimaerpcategory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimaerpproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.bimaerpcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='bimaerpproduct',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='bimaerpproduct',
            name='dimension',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dimension'),
        ),
        migrations.AlterField(
            model_name='bimaerpproduct',
            name='ean13',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='EAN13'),
        ),
        migrations.AlterField(
            model_name='bimaerpproduct',
            name='lead_time',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Lead Time'),
        ),
        migrations.AlterField(
            model_name='bimaerpproduct',
            name='maximum_stock_level',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Maximum Stock Level'),
        ),
        migrations.AlterField(
            model_name='bimaerpproduct',
            name='minimum_stock_level',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Minimum Stock Level'),
        ),
        migrations.AlterField(
            model_name='bimaerpproduct',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='bimaerpproduct',
            name='price_calculation_method',
            field=models.CharField(choices=[('MANUAL', 'Manual Price'), ('PERCENTAGE', 'Price based on Percentage')], max_length=50, verbose_name='Price Calculation Method'),
        ),
        migrations.AlterField(
            model_name='bimaerpproduct',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='Purchase Price'),
        ),
        migrations.AlterField(
            model_name='bimaerpproduct',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='bimaerpproduct',
            name='reference',
            field=models.CharField(max_length=255, unique=True, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='bimaerpproduct',
            name='reorder_point',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Reorder Point'),
        ),
        migrations.AlterField(
            model_name='bimaerpproduct',
            name='sell_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Sell Percentage'),
        ),
        migrations.AlterField(
            model_name='bimaerpproduct',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='Sell Price'),
        ),
        migrations.AlterField(
            model_name='bimaerpproduct',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='bimaerpproduct',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('OUT_OF_STOCK', 'Out of Stock:'), ('IN_TRANSIT', 'In transit'), ('DISCONTINUED', 'Discontinued'), ('NOT_FOR_SALE', 'Not for sale')], max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='bimaerpproduct',
            name='type',
            field=models.CharField(choices=[('STOCKABLE_PRODUCT', 'Stockable Products'), ('SERVICE_PRODUCTS', 'Service Products'), ('PRODUCTION_PRODUCTS', 'Production Products')], max_length=255, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='bimaerpproduct',
            name='unit_of_measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.bimaerpunitofmeasure', verbose_name='Unit of Measure'),
        ),
        migrations.AlterField(
            model_name='bimaerpproduct',
            name='vat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.bimaerpvat', verbose_name='VAT'),
        ),
        migrations.AlterField(
            model_name='bimaerpproduct',
            name='virtual_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Virtual Quantity'),
        ),
        migrations.AlterField(
            model_name='bimaerpproduct',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Weight'),
        ),
    ]
