# Generated by Django 4.2.2 on 2023-07-06 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0032_alter_bimaerpproduct_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bimaerpcategory',
            options={'default_permissions': (), 'ordering': ['name'], 'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='bimaerppartner',
            options={'default_permissions': (), 'ordering': ['-created'], 'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='bimaerpproduct',
            options={'default_permissions': (), 'ordering': ['name'], 'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='bimaerppurchasedocument',
            options={'default_permissions': (), 'ordering': ['-created'], 'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='bimaerppurchasedocumentproduct',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='bimaerpsaledocument',
            options={'default_permissions': (), 'ordering': ['-created'], 'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='bimaerpsaledocumentproduct',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='bimaerpunitofmeasure',
            options={'default_permissions': (), 'ordering': ['name'], 'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='bimaerpvat',
            options={'default_permissions': (), 'ordering': ['name'], 'permissions': []},
        ),
    ]
