# Generated by Django 4.2.2 on 2023-07-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0033_alter_bimaerpcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimaerppartner',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='bimaerppartner',
            name='company_activity',
            field=models.CharField(blank=True, null=True, verbose_name='Company Activity'),
        ),
        migrations.AlterField(
            model_name='bimaerppartner',
            name='company_ape_code',
            field=models.CharField(blank=True, null=True, verbose_name='Company APE Code'),
        ),
        migrations.AlterField(
            model_name='bimaerppartner',
            name='company_ape_text',
            field=models.CharField(blank=True, null=True, verbose_name='Company APE Text'),
        ),
        migrations.AlterField(
            model_name='bimaerppartner',
            name='company_capital',
            field=models.CharField(blank=True, null=True, verbose_name='Company Capital'),
        ),
        migrations.AlterField(
            model_name='bimaerppartner',
            name='company_date_creation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Company Date Creation'),
        ),
        migrations.AlterField(
            model_name='bimaerppartner',
            name='company_date_registration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Company Date Registration'),
        ),
        migrations.AlterField(
            model_name='bimaerppartner',
            name='company_date_struck_off',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Company Date Struck Off'),
        ),
        migrations.AlterField(
            model_name='bimaerppartner',
            name='company_name',
            field=models.CharField(blank=True, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='bimaerppartner',
            name='company_siren',
            field=models.CharField(blank=True, null=True, verbose_name='Company Siren'),
        ),
        migrations.AlterField(
            model_name='bimaerppartner',
            name='company_siret',
            field=models.CharField(blank=True, null=True, verbose_name='Company Siret'),
        ),
        migrations.AlterField(
            model_name='bimaerppartner',
            name='company_type',
            field=models.CharField(blank=True, choices=[('SOLE_PROPRIETORSHIP', 'Sole proprietorship'), ('GENERAL_PARTNERSHIP', 'General partnership'), ('LIMITED_PARTNERSHIP', 'Limited partnership'), ('PUBLIC_LIMITED_COMPANY_PLC', 'Public limited company(PLC)'), ('LIMITED_LIABILITY_COMPANY_LLC', 'Limited liability company(LLC)'), ('SIMPLIFIED_JOINT_STOCK', 'Simplified joint - stock'), ('COMPANY_PARTNERSHIP_LIMITED_BY_SHARES', 'company Partnership limited by shares'), ('COOPERATIVE_SOCIETY', 'Cooperative society'), ('UNINCORPORATED_JOINT_VENTURE', 'Unincorporated joint venture'), ('JOINT_STOCK_COMPANY', 'Joint - stock company')], max_length=256, null=True, verbose_name='Company Type'),
        ),
        migrations.AlterField(
            model_name='bimaerppartner',
            name='credit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='Credit'),
        ),
        migrations.AlterField(
            model_name='bimaerppartner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='bimaerppartner',
            name='fax',
            field=models.CharField(blank=True, null=True, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='bimaerppartner',
            name='first_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='bimaerppartner',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=32, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='bimaerppartner',
            name='id_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='ID Number'),
        ),
        migrations.AlterField(
            model_name='bimaerppartner',
            name='is_customer',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is Customer'),
        ),
        migrations.AlterField(
            model_name='bimaerppartner',
            name='is_supplier',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is Supplier'),
        ),
        migrations.AlterField(
            model_name='bimaerppartner',
            name='last_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='bimaerppartner',
            name='note',
            field=models.CharField(blank=True, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='bimaerppartner',
            name='partner_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company')], max_length=128, verbose_name='Partner Type'),
        ),
        migrations.AlterField(
            model_name='bimaerppartner',
            name='phone',
            field=models.CharField(blank=True, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='bimaerppartner',
            name='rcs_number',
            field=models.CharField(blank=True, null=True, verbose_name='RCS Number'),
        ),
        migrations.AlterField(
            model_name='bimaerppartner',
            name='social_security_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Social Security Number'),
        ),
        migrations.AlterField(
            model_name='bimaerppartner',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked')], max_length=32, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='bimaerppartner',
            name='vat_id_number',
            field=models.CharField(blank=True, null=True, verbose_name='VAT ID Number'),
        ),
    ]
