# Generated by Django 4.2.2 on 2023-07-21 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0034_alter_bimaerppartner_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimaerpcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='erp.bimaerpcategory'),
        ),
    ]
