# Generated by Django 4.2.3 on 2023-07-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0035_alter_bimaerpcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimaerpunitofmeasure',
            name='is_default_for_service_product',
            field=models.BooleanField(default=False),
        ),
    ]
