# Generated by Django 4.2.3 on 2023-08-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0037_bimaerpsaledocument_recurring_cycle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bimaerpsaledocument",
            name="recurring_cycle",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UNDEFINED", "INDEFINIE"),
                    ("END_AT", "TERMINE LE"),
                    ("END_AFTER", "TERMINE APRES"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bimaerpsaledocument",
            name="recurring_interval_type_custom_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DAY", "JOUR"),
                    ("WEEK", "SEMAINE"),
                    ("MONTH", "MOIS"),
                    ("YEAR", "ANNEE"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbimaerpsaledocument",
            name="recurring_cycle",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UNDEFINED", "INDEFINIE"),
                    ("END_AT", "TERMINE LE"),
                    ("END_AFTER", "TERMINE APRES"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbimaerpsaledocument",
            name="recurring_interval_type_custom_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DAY", "JOUR"),
                    ("WEEK", "SEMAINE"),
                    ("MONTH", "MOIS"),
                    ("YEAR", "ANNEE"),
                ],
                null=True,
            ),
        ),
    ]
