# Generated by Django 4.2.3 on 2023-08-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0038_alter_bimaerpsaledocument_recurring_cycle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bimaerpsaledocument",
            name="is_recurring_ended",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="bimaerpsaledocument",
            name="is_recurring_parent",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="historicalbimaerpsaledocument",
            name="is_recurring_ended",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="historicalbimaerpsaledocument",
            name="is_recurring_parent",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="bimaerpsaledocument",
            name="recurring_initial_parent_id",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="bimaerpsaledocument",
            name="recurring_initial_parent_public_id",
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="historicalbimaerpsaledocument",
            name="recurring_initial_parent_id",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="historicalbimaerpsaledocument",
            name="recurring_initial_parent_public_id",
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
