# Generated by Django 4.2.3 on 2023-08-08 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("erp", "0040_bimaerpsaledocument_recurring_last_generated_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bimaerpsaledocument",
            name="recurring_reactivated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reactivated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bimaerpsaledocument",
            name="recurring_reactivated_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="bimaerpsaledocument",
            name="recurring_reason_reactivated",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="bimaerpsaledocument",
            name="recurring_reason_stop",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="bimaerpsaledocument",
            name="recurring_stopped_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stopped_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalbimaerpsaledocument",
            name="recurring_reactivated_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalbimaerpsaledocument",
            name="recurring_reactivated_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalbimaerpsaledocument",
            name="recurring_reason_reactivated",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalbimaerpsaledocument",
            name="recurring_reason_stop",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalbimaerpsaledocument",
            name="recurring_stopped_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
