# Generated by Django 4.2.3 on 2023-08-08 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("erp", "0041_bimaerpsaledocument_recurring_reactivated_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalbimaerpsaledocument",
            name="history_user",
        ),
        migrations.AddField(
            model_name="historicalbimaerpsaledocument",
            name="history_user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
