# Generated by Django 4.2.3 on 2023-08-08 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("erp", "0042_remove_historicalbimaerpsaledocument_history_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalbimaerpsaledocument",
            name="history_user_id",
        ),
        migrations.AddField(
            model_name="bimaerpsaledocument",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="document_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
