# Generated by Django 4.2.3 on 2023-08-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0045_historicalbimaerpsaledocument_history_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="bimaerpsaledocument",
            name="recurring_next_generated_day",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalbimaerpsaledocument",
            name="recurring_next_generated_day",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
