# Generated by Django 4.2.3 on 2023-08-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0046_bimaerpsaledocument_recurring_next_generated_day_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bimaerppurchasedocument",
            name="is_recurring",
        ),
        migrations.RemoveField(
            model_name="bimaerppurchasedocument",
            name="recurring_interval",
        ),
        migrations.RemoveField(
            model_name="historicalbimaerppurchasedocument",
            name="is_recurring",
        ),
        migrations.RemoveField(
            model_name="historicalbimaerppurchasedocument",
            name="recurring_interval",
        ),
        migrations.AlterField(
            model_name="bimaerppurchasedocument",
            name="type",
            field=models.CharField(
                choices=[
                    ("QUOTE", "Quote"),
                    ("ORDER", "ORDER"),
                    ("INVOICE", "Invoice"),
                    ("CREDIT_NOTE", "Credit note"),
                    ("RFQ", "Request for Quotation"),
                ],
                default="Quote",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbimaerppurchasedocument",
            name="type",
            field=models.CharField(
                choices=[
                    ("QUOTE", "Quote"),
                    ("ORDER", "ORDER"),
                    ("INVOICE", "Invoice"),
                    ("CREDIT_NOTE", "Credit note"),
                    ("RFQ", "Request for Quotation"),
                ],
                default="Quote",
                max_length=128,
            ),
        ),
    ]
