# Generated by Django 4.2.3 on 2023-08-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0047_remove_bimaerppurchasedocument_is_recurring_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bimaerppurchasedocument",
            name="number_at_partner",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="historicalbimaerppurchasedocument",
            name="number_at_partner",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
