# Generated by Django 4.2.3 on 2023-08-17 09:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0048_alter_bimaerppurchasedocument_number_at_partner_and_more"),
    ]
