# Generated by Django 4.2.3 on 2023-08-28 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("treasury", "0018_bimatreasurytransaction_reference_and_more"),
        ("erp", "0052_remove_bimaerpsaledocument_payment_terms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bimaerpsaledocument",
            name="payment_terms",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="treasury.bimatreasurypaymentterm",
                verbose_name="Payment Terms",
            ),
        ),
        migrations.AddField(
            model_name="historicalbimaerpsaledocument",
            name="payment_terms",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="treasury.bimatreasurypaymentterm",
                verbose_name="Payment Terms",
            ),
        ),
    ]
