# Generated by Django 4.2.3 on 2023-08-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treasury", "0019_transactionsaledocumentpayment"),
        ("erp", "0053_bimaerpsaledocument_payment_terms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bimaerpsaledocument",
            name="transactions",
            field=models.ManyToManyField(
                related_name="sale_documents",
                through="treasury.TransactionSaleDocumentPayment",
                to="treasury.bimatreasurytransaction",
            ),
        ),
    ]
