# Generated by Django 4.2.3 on 2023-08-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0054_bimaerpsaledocument_transactions"),
    ]

    operations = [
        migrations.AddField(
            model_name="bimaerpsaledocument",
            name="amount_paid",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=0,
                max_digits=18,
                null=True,
                verbose_name="Amount Paid",
            ),
        ),
        migrations.AddField(
            model_name="historicalbimaerpsaledocument",
            name="amount_paid",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=0,
                max_digits=18,
                null=True,
                verbose_name="Amount Paid",
            ),
        ),
    ]
