# Generated by Django 4.2.3 on 2023-09-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0059_bimaerppurchasedocument_payment_terms_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bimaerppurchasedocument",
            name="payment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NOT_PAID", "NOT_PAID"),
                    ("PARTIAL_PAID", "PARTIAL_PAID"),
                    ("PAID", "PAID"),
                ],
                default="NOT_PAID",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bimaerpsaledocument",
            name="payment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NOT_PAID", "NOT_PAID"),
                    ("PARTIAL_PAID", "PARTIAL_PAID"),
                    ("PAID", "PAID"),
                ],
                default="NOT_PAID",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbimaerppurchasedocument",
            name="payment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NOT_PAID", "NOT_PAID"),
                    ("PARTIAL_PAID", "PARTIAL_PAID"),
                    ("PAID", "PAID"),
                ],
                default="NOT_PAID",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbimaerpsaledocument",
            name="payment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NOT_PAID", "NOT_PAID"),
                    ("PARTIAL_PAID", "PARTIAL_PAID"),
                    ("PAID", "PAID"),
                ],
                default="NOT_PAID",
                null=True,
            ),
        ),
    ]
