# Generated by Django 4.2.3 on 2023-09-19 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0061_bimaerppurchasedocument_days_in_late_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bimaerppurchasedocument",
            options={
                "default_permissions": (),
                "ordering": ["-date"],
                "permissions": [],
            },
        ),
        migrations.AlterModelOptions(
            name="bimaerpsaledocument",
            options={
                "default_permissions": (),
                "ordering": ["-date"],
                "permissions": [],
            },
        ),
    ]
